# Boss Fight

```{r, results='asis', echo=FALSE}
if (knitr::is_html_output()) {
  cat('<iframe width="100%" height="400" src="https://www.youtube.com/embed/THEOJOoJmRU?si=-iY-vpsc2Y0LJamC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>')
}
```

**Wow**. You’ve made it to the end of the BIOS103 QS course! Congratulations. Over the semester, you’ve built an impressive toolbox of skills. By now, you should be able to:

- Import data files in Excel and R.
- Clean, subset, and filter data in Excel and R.
- Generate tables of summary statistics in Excel and R.
- Perform a one-way ANOVA in Excel and R, and interpret the results.
- Conduct post-hoc tests using Bonferroni-corrected t-tests in Excel.
- Perform post-hoc tests using Tukey’s HSD in R.
- Conduct linear regression in Excel and R, and interpret the results.
- Generate boxplots, scatterplots, and histograms in Excel and R.
- Perform a two-way ANOVA in R.
- Conduct multiple linear regression (MLR) in R.
- Use pre-existing R code to parse FASTA files and perform basic bioinformatics on DNA sequences.
- Leverage R code and packages to perform automated image analysis on multiple files.

Phew! When you put it all together, that’s an incredible skill set.

**But it’s not over just yet**. Are you ready for one last challenge? Enter the **Boss Fight**: 
Four questions to test your mettle. Three have been adapted from the past four weeks (don’t worry, no yeast or mushrooms this time!). The final question is a fun one to wrap things up.

This time, I’m not giving you any pre-written code. You’ll need to recycle and tweak what you’ve already encountered in Chapters 6, 8, and 9.

And here’s your final **learning objective**:

- Learn that it's OK to **forget everything** when it comes to code.

Coding isn’t about memorising everything, it’s about knowing where to look and how to apply what you find. I’ve been coding for over a decade, and I still Google solutions regularly. The important thing is that you are now equipped with the tools and confidence to dive back into R next September, ready to tackle advanced quantitative skills with a solid foundation.

As always, the demonstrator team will provide direct support in the Workshop channel on Microsoft Teams for this final challenge. For those attending in person, I’ll be bringing a limited stock of mince pies to the Thursday 9–11 AM workshop session in the Randall Building. You’re all warmly invited to join us.

**Merry Christmas and a Happy New Year!**

Rob Treharne. 11/12/2024
