<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Statistics in R: Part I | Quantiative Skills in Biosciences I</title>
  <meta name="description" content="6 Statistics in R: Part I | Quantiative Skills in Biosciences I" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Statistics in R: Part I | Quantiative Skills in Biosciences I" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Statistics in R: Part I | Quantiative Skills in Biosciences I" />
  
  
  

<meta name="author" content="R. E. Treharne" />


<meta name="date" content="2024-10-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-r-part-ii-visualisation.html"/>
<link rel="next" href="statistics-in-r-part-ii.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to Excel and R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#estimating-the-volume-of-a-snail"><i class="fa fa-check"></i><b>1.1</b> Estimating the Volume of a Snail</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#download-and-import-the-csv-file"><i class="fa fa-check"></i><b>1.1.1</b> Download and Import the CSV File</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#calculate-volume-v-in-excel"><i class="fa fa-check"></i><b>1.1.2</b> Calculate Volume <span class="math inline">\(V\)</span> in Excel</a></li>
<li class="chapter" data-level="1.1.3" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#add-a-linear-trendline-and-equation"><i class="fa fa-check"></i><b>1.1.3</b> Add a Linear Trendline and Equation</a></li>
<li class="chapter" data-level="1.1.4" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#estimation-of-volume-for-a-snail-with-mass-10g"><i class="fa fa-check"></i><b>1.1.4</b> Estimation of Volume for a Snail with Mass 10g</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#getting-ready-for-R"><i class="fa fa-check"></i><b>1.2</b> Getting Ready for R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#download-and-install-windows-and-mac-only"><i class="fa fa-check"></i><b>1.2.1</b> Download and Install (Windows and Mac only)</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#creating-your-first-r-project-in-rstudio"><i class="fa fa-check"></i><b>1.2.2</b> Creating Your First R Project in RStudio</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#something-more-complicated"><i class="fa fa-check"></i><b>1.2.3</b> Something More Complicated</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#complete-your-weekly-assignments"><i class="fa fa-check"></i><b>1.3</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html"><i class="fa fa-check"></i><b>2</b> Summarising Data and ANOVA in Excel</a>
<ul>
<li class="chapter" data-level="2.1" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#summarising-data"><i class="fa fa-check"></i><b>2.1</b> Summarising Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#download-and-import-the-csv-file-1"><i class="fa fa-check"></i><b>2.1.1</b> Download and Import the CSV File</a></li>
<li class="chapter" data-level="2.1.2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#generating-a-summary-table"><i class="fa fa-check"></i><b>2.1.2</b> Generating a Summary Table</a></li>
<li class="chapter" data-level="2.1.3" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#presenting-your-summary-table"><i class="fa fa-check"></i><b>2.1.3</b> Presenting Your Summary Table</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#anova"><i class="fa fa-check"></i><b>2.2</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#grouped-boxplots-in-excel"><i class="fa fa-check"></i><b>2.2.1</b> Grouped Boxplots in Excel</a></li>
<li class="chapter" data-level="2.2.2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#constructing-testable-hypotheses"><i class="fa fa-check"></i><b>2.2.2</b> Constructing Testable Hypotheses</a></li>
<li class="chapter" data-level="2.2.3" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#performing-a-one-way-anova-in-excel"><i class="fa fa-check"></i><b>2.2.3</b> Performing a One-Way Anova in Excel</a></li>
<li class="chapter" data-level="2.2.4" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#post-hoc-tests"><i class="fa fa-check"></i><b>2.2.4</b> Performing Post-hoc Tests in Excel</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#complete-your-weekly-assignments-1"><i class="fa fa-check"></i><b>2.3</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html"><i class="fa fa-check"></i><b>3</b> Calibration Curves and Linear Regression in Excel</a>
<ul>
<li class="chapter" data-level="3.1" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#calibration-curves"><i class="fa fa-check"></i><b>3.1</b> Calibration Curves</a></li>
<li class="chapter" data-level="3.2" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#linear-regression"><i class="fa fa-check"></i><b>3.2</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#the-linear-regression-equation"><i class="fa fa-check"></i><b>3.2.1</b> The Linear Regression Equation</a></li>
<li class="chapter" data-level="3.2.2" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#performing-a-linear-regression-in-excel"><i class="fa fa-check"></i><b>3.2.2</b> Performing a Linear Regression in Excel</a></li>
<li class="chapter" data-level="3.2.3" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#interpreting-your-linear-regression"><i class="fa fa-check"></i><b>3.2.3</b> Interpreting Your Linear Regression</a></li>
<li class="chapter" data-level="3.2.4" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#making-predictions-with-our-model"><i class="fa fa-check"></i><b>3.2.4</b> Making Predictions with Our Model</a></li>
<li class="chapter" data-level="3.2.5" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#extending-to-multiple-variables"><i class="fa fa-check"></i><b>3.2.5</b> Extending to Multiple Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#complete-your-weekly-assignments-2"><i class="fa fa-check"></i><b>3.3</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html"><i class="fa fa-check"></i><b>4</b> Introduction to R: Part I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#reading-and-inspecting-data"><i class="fa fa-check"></i><b>4.1</b> Reading and Inspecting Data</a></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#subsetting"><i class="fa fa-check"></i><b>4.2</b> Subsetting</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#slicing"><i class="fa fa-check"></i><b>4.2.1</b> Slicing</a></li>
<li class="chapter" data-level="4.2.2" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#filtering"><i class="fa fa-check"></i><b>4.2.2</b> Filtering</a></li>
<li class="chapter" data-level="4.2.3" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#so-what"><i class="fa fa-check"></i><b>4.2.3</b> So what?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#summarising-data-in-r"><i class="fa fa-check"></i><b>4.3</b> Summarising Data in R</a></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#complete-your-weekly-assignments-3"><i class="fa fa-check"></i><b>4.4</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html"><i class="fa fa-check"></i><b>5</b> Introduction to R part II: Visualisation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#mushroom-compost-scenario"><i class="fa fa-check"></i><b>5.1</b> Mushroom Compost Scenario</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#the-dataset"><i class="fa fa-check"></i><b>5.1.1</b> The dataset</a></li>
<li class="chapter" data-level="5.1.2" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#further-information"><i class="fa fa-check"></i><b>5.1.2</b> Further information</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#inspecting-and-summarising"><i class="fa fa-check"></i><b>5.2</b> Inspecting and Summarising</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#summary-table"><i class="fa fa-check"></i><b>5.2.1</b> Summary Table</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#histogram"><i class="fa fa-check"></i><b>5.3</b> Histogram</a></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#grouped-boxplot"><i class="fa fa-check"></i><b>5.4</b> Grouped Boxplot</a></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#scatterplot"><i class="fa fa-check"></i><b>5.5</b> Scatterplot</a></li>
<li class="chapter" data-level="5.6" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#just-for-fun"><i class="fa fa-check"></i><b>5.6</b> Just for Fun</a></li>
<li class="chapter" data-level="5.7" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#complete-your-weekly-assignments-4"><i class="fa fa-check"></i><b>5.7</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html"><i class="fa fa-check"></i><b>6</b> Statistics in R: Part I</a>
<ul>
<li class="chapter" data-level="6.1" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#one-way-anova-in-r"><i class="fa fa-check"></i><b>6.1</b> One-Way ANOVA in R</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#importing-data-from-an-online-source"><i class="fa fa-check"></i><b>6.1.1</b> Importing Data from an Online Source</a></li>
<li class="chapter" data-level="6.1.2" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#summarising-descriptive-statistics"><i class="fa fa-check"></i><b>6.1.2</b> Summarising (Descriptive Statistics)</a></li>
<li class="chapter" data-level="6.1.3" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#grouped-boxplots-in-r"><i class="fa fa-check"></i><b>6.1.3</b> Grouped Boxplots in R</a></li>
<li class="chapter" data-level="6.1.4" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#conducting-a-one-way-anova"><i class="fa fa-check"></i><b>6.1.4</b> Conducting a One-Way ANOVA</a></li>
<li class="chapter" data-level="6.1.5" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#post-hoc-tests-1"><i class="fa fa-check"></i><b>6.1.5</b> Post-Hoc Tests</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#two-way-anova-in-r"><i class="fa fa-check"></i><b>6.2</b> Two-way ANOVA in R</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#importing-and-cleaning-the-data"><i class="fa fa-check"></i><b>6.2.1</b> Importing and Cleaning the Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#visualising-the-data"><i class="fa fa-check"></i><b>6.2.2</b> Visualising the data</a></li>
<li class="chapter" data-level="6.2.3" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#conducting-a-two-way-anova"><i class="fa fa-check"></i><b>6.2.3</b> Conducting a Two-Way ANOVA</a></li>
<li class="chapter" data-level="6.2.4" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#post-hoc-tests-2"><i class="fa fa-check"></i><b>6.2.4</b> Post-Hoc tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html"><i class="fa fa-check"></i><b>7</b> Statistics in R: Part II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#linear-regression-in-r"><i class="fa fa-check"></i><b>7.1</b> Linear Regression in R</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#reading-and-inspecting-the-data"><i class="fa fa-check"></i><b>7.1.1</b> Reading and inspecting the data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix: Teach yourself R.</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#linkedin-learning"><i class="fa fa-check"></i>LinkedIn Learning</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#youtube"><i class="fa fa-check"></i>YouTube</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#books"><i class="fa fa-check"></i>Books</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="feedback.html"><a href="feedback.html"><i class="fa fa-check"></i>Appendix II: Feedback.</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantiative Skills in Biosciences I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics-in-r-part-i" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Statistics in R: Part I<a href="statistics-in-r-part-i.html#statistics-in-r-part-i" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>If you are currently participating in a timetabled BIOS103 QS workshop, please ensure that you cover <strong>all of this section’s content</strong> and complete this week’s <strong>formative and summative assessments</strong> in the BIOS103 Canvas Course.</p>
<p>The aim of this chapter is to show that there are often several ways to approach data analysis. Here, we’ll use R to perform tasks we’ve previously done in Excel. Why make the switch? While Excel is widely used (and is still extremely useful), R can greatly reduce the need for manual data transformations that Excel often requires, making data handling much easier and more efficient. Also, creating R scripts provides a clear, reproducible record of your analysis which is incredibly important for anyone who wishes to repeat your analysis and confirm your results.</p>
<p>Key <strong>learning objectives</strong> for this chapter include:</p>
<ul>
<li>Reading data direct from the web using R.</li>
<li>Organising and cleaning your data in R ready for analysis.</li>
<li>Performing a One-Way ANOVA and post-hoc tests in R.</li>
<li>Performing a Two-Way ANOVA and post-hoc tests in R.</li>
<li>Visualising relationships between two independent variables and a dependent one.</li>
</ul>
<div id="one-way-anova-in-r" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> One-Way ANOVA in R<a href="statistics-in-r-part-i.html#one-way-anova-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This section is almost a complete re-run of section <a href="summarising-data-and-anova-in-excel.html#anova">2.2</a>. Except what we did in Excel, we’ll learn to do in R. I strongly recommend that you have a quick scroll through the whole of section <a href="summarising-data-and-anova-in-excel.html#anova">2.2</a> <strong>right now</strong> to refresh your memory. Seriously, do it.</p>
<iframe width="100%" height="400" src="https://www.youtube.com/embed/LjRPJy-XKG4?si=ZDASeECEBathkhl6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
</iframe>
<p><br></p>
<div id="importing-data-from-an-online-source" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> Importing Data from an Online Source<a href="statistics-in-r-part-i.html#importing-data-from-an-online-source" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before we begin, did you know that the humble <code>read.csv()</code> function can also read a CSV file from a URL, making it extremely easy to work with datasets stored online.</p>
<p>The code below imports a CSV file containing zebrafish data, which includes information about the length of zebrafish embryos under various concentrations of alcohol. The <code>read.csv()</code> function fetches the data from the provided URL, which points to a raw GitHub file.</p>
<p>Create a new R project for this week and start a new script file. Copy the following lines the the file and run them.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="statistics-in-r-part-i.html#cb48-1" tabindex="-1"></a><span class="co"># Read data direct from the web!</span></span>
<span id="cb48-2"><a href="statistics-in-r-part-i.html#cb48-2" tabindex="-1"></a>zebrafish_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/rtreharne/qs/refs/heads/main/data/02/zebrafish_999.csv&quot;</span>)</span>
<span id="cb48-3"><a href="statistics-in-r-part-i.html#cb48-3" tabindex="-1"></a></span>
<span id="cb48-4"><a href="statistics-in-r-part-i.html#cb48-4" tabindex="-1"></a><span class="co"># Convert the conc_pc column into a factor. IMPORTANT!</span></span>
<span id="cb48-5"><a href="statistics-in-r-part-i.html#cb48-5" tabindex="-1"></a>zebrafish_data<span class="sc">$</span>conc_pc <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(zebrafish_data<span class="sc">$</span>conc_pc)</span>
<span id="cb48-6"><a href="statistics-in-r-part-i.html#cb48-6" tabindex="-1"></a></span>
<span id="cb48-7"><a href="statistics-in-r-part-i.html#cb48-7" tabindex="-1"></a><span class="co"># Inspect the data</span></span>
<span id="cb48-8"><a href="statistics-in-r-part-i.html#cb48-8" tabindex="-1"></a><span class="fu">head</span>(zebrafish_data)</span></code></pre></div>
<pre><code>##     id conc_pc length_micron
## 1 2146       0        2103.4
## 2 3853       0        2703.3
## 3 2313       2        2279.5
## 4 1638     2.5        2020.8
## 5 1669     2.5        1708.4
## 6 2644     2.5        2256.3</code></pre>
<p>After importing the data, we convert the <code>conc_pc</code> column (which represents alcohol concentration percentages) into a factor variable using <code>as.factor()</code>. This is <strong>important</strong> because factors are categorical variables in R, and we’ll treat them as such in our analysis. Note that if you don’t perform this step then you’ll get errors when trying to do ANOVA.</p>
<p>Finally, the <code>head()</code> function is used to display the first few rows of the data, giving us an overview of its structure. This is a common way to check that the data has been loaded correctly and to understand the initial format of the dataset.</p>
<p>By importing data directly from an online source, you can quickly access and analyse datasets without needing to manually download and load files, streamlining your workflow. You’re welcome.</p>
</div>
<div id="summarising-descriptive-statistics" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> Summarising (Descriptive Statistics)<a href="statistics-in-r-part-i.html#summarising-descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The code below will calculate descriptive statistics for the zebrafish dataset to summarise the length of the zebrafish embryos (<code>length_micron</code>) across different alcohol concentrations (<code>conc_pc</code>). Remember, descriptive statistics provide a quick overview of the central tendency and variability within the data, helping us understand patterns and outliers.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="statistics-in-r-part-i.html#cb50-1" tabindex="-1"></a><span class="co"># This code extends the code block above.</span></span>
<span id="cb50-2"><a href="statistics-in-r-part-i.html#cb50-2" tabindex="-1"></a></span>
<span id="cb50-3"><a href="statistics-in-r-part-i.html#cb50-3" tabindex="-1"></a><span class="co"># Calculate summary statistics for each group</span></span>
<span id="cb50-4"><a href="statistics-in-r-part-i.html#cb50-4" tabindex="-1"></a>zebrafish_summary <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(length_micron <span class="sc">~</span> conc_pc, zebrafish_data, <span class="cf">function</span>(x) </span>
<span id="cb50-5"><a href="statistics-in-r-part-i.html#cb50-5" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">Mean =</span> <span class="fu">mean</span>(x), <span class="at">Median =</span> <span class="fu">median</span>(x), <span class="at">Max =</span> <span class="fu">max</span>(x), <span class="at">Min =</span> <span class="fu">min</span>(x), <span class="at">SD =</span> <span class="fu">sd</span>(x)))</span>
<span id="cb50-6"><a href="statistics-in-r-part-i.html#cb50-6" tabindex="-1"></a></span>
<span id="cb50-7"><a href="statistics-in-r-part-i.html#cb50-7" tabindex="-1"></a><span class="co"># Convert the list to data frame</span></span>
<span id="cb50-8"><a href="statistics-in-r-part-i.html#cb50-8" tabindex="-1"></a>zebrafish_summary <span class="ot">&lt;-</span> <span class="fu">do.call</span>(data.frame, zebrafish_summary)</span>
<span id="cb50-9"><a href="statistics-in-r-part-i.html#cb50-9" tabindex="-1"></a></span>
<span id="cb50-10"><a href="statistics-in-r-part-i.html#cb50-10" tabindex="-1"></a><span class="co"># Inspect the summary</span></span>
<span id="cb50-11"><a href="statistics-in-r-part-i.html#cb50-11" tabindex="-1"></a><span class="fu">print</span>(zebrafish_summary)</span></code></pre></div>
<pre><code>##   conc_pc length_micron.Mean length_micron.Median length_micron.Max
## 1       0           2410.874              2451.15            2890.1
## 2     1.5           2405.318              2397.05            2975.6
## 3       2           2300.736              2279.50            2666.3
## 4     2.5           2105.539              2157.30            2692.1
##   length_micron.Min length_micron.SD
## 1            1859.5         251.2151
## 2            1962.4         255.3249
## 3            1746.3         206.8577
## 4            1548.2         266.6929</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="statistics-in-r-part-i.html#cb52-1" tabindex="-1"></a><span class="co"># Save to file</span></span>
<span id="cb52-2"><a href="statistics-in-r-part-i.html#cb52-2" tabindex="-1"></a><span class="fu">write.csv</span>(zebrafish_summary, <span class="at">file =</span> <span class="st">&quot;zebrafish_summary.csv&quot;</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>We begin by using the <code>aggregate()</code> function, which allows us to group the data by alcohol concentration (<code>conc_pc</code>) and calculate several statistics for each group: the mean, median, maximum, minimum, and standard deviation (SD). These metrics help us understand the typical value (mean and median) and the spread (max, min, SD) within each concentration level.</p>
<p>Once the summary statistics have been calculated, we convert the output from the aggregate() function (which is in list form) into a more manageable data frame format using the <code>do.call(data.frame, ...)</code> function. This makes it easier to inspect and manipulate the results.</p>
<p>To examine the summary statistics, we <code>print()</code> the <code>zebrafish_summary</code> dataframe. This provides an organised view of the key statistics for each group in the dataset.</p>
<p>Finally, it is a good practice to save your results to a file. In this case, we save the <code>zebrafish_summary</code> dataframe to a CSV file, allowing us to easily store, share, or reload the data for further analysis. The <code>write.csv()</code> function does this, ensuring the summary statistics are saved in a structured format, without row names, for easy use in future work. As before, you can import this .csv into Excel to style it for a report.</p>
</div>
<div id="grouped-boxplots-in-r" class="section level3 hasAnchor" number="6.1.3">
<h3><span class="header-section-number">6.1.3</span> Grouped Boxplots in R<a href="statistics-in-r-part-i.html#grouped-boxplots-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As before, the best way to visualise our dataset is using a grouped boxplot. Can you remember how fiddly this was in Excel? We had to create a pivot table before we could make a plot - yuck. Not so in R! The code below let’s us get the job done quickly, without faffing to produce the plot shown in figure <a href="statistics-in-r-part-i.html#fig:boxplot">6.1</a>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="statistics-in-r-part-i.html#cb53-1" tabindex="-1"></a><span class="co"># This code extends the code blocks above.</span></span>
<span id="cb53-2"><a href="statistics-in-r-part-i.html#cb53-2" tabindex="-1"></a></span>
<span id="cb53-3"><a href="statistics-in-r-part-i.html#cb53-3" tabindex="-1"></a><span class="co"># Generate a grouped boxplot</span></span>
<span id="cb53-4"><a href="statistics-in-r-part-i.html#cb53-4" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb53-5"><a href="statistics-in-r-part-i.html#cb53-5" tabindex="-1"></a>  length_micron <span class="sc">~</span> conc_pc, <span class="at">data =</span> zebrafish_data,</span>
<span id="cb53-6"><a href="statistics-in-r-part-i.html#cb53-6" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb53-7"><a href="statistics-in-r-part-i.html#cb53-7" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;Alcohol Conc. (%)&quot;</span>,</span>
<span id="cb53-8"><a href="statistics-in-r-part-i.html#cb53-8" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">&quot;Embryo Length (microns)&quot;</span>,</span>
<span id="cb53-9"><a href="statistics-in-r-part-i.html#cb53-9" tabindex="-1"></a>  <span class="at">col =</span> <span class="st">&quot;lightblue&quot;</span></span>
<span id="cb53-10"><a href="statistics-in-r-part-i.html#cb53-10" tabindex="-1"></a>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:boxplot"></span>
<img src="img/08/boxplot.png" alt="Distribution of Zebrafish embryo lengths organised by Alcohol treaments." width="100%" />
<p class="caption">
Figure 6.1: Distribution of Zebrafish embryo lengths organised by Alcohol treaments.
</p>
</div>
<p>My interpretation of the plot is exactly the same as that discussed in section <a href="summarising-data-and-anova-in-excel.html#grouped-boxplots-in-excel">2.2.1</a>.</p>
</div>
<div id="conducting-a-one-way-anova" class="section level3 hasAnchor" number="6.1.4">
<h3><span class="header-section-number">6.1.4</span> Conducting a One-Way ANOVA<a href="statistics-in-r-part-i.html#conducting-a-one-way-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We are about to perform a One-Way Analysis of Variance (ANOVA) in R to examine whether there is a statistically significant difference in zebrafish embryo lengths across different alcohol concentrations. ANOVA allows us to compare the means of more than two groups to determine if any of the group means are different from each other.</p>
<p>The code below does the job in a single line. Beat that Excel!</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="statistics-in-r-part-i.html#cb54-1" tabindex="-1"></a><span class="co"># This code extends the code blocks above.</span></span>
<span id="cb54-2"><a href="statistics-in-r-part-i.html#cb54-2" tabindex="-1"></a></span>
<span id="cb54-3"><a href="statistics-in-r-part-i.html#cb54-3" tabindex="-1"></a><span class="co"># Perform a One-Way ANOVA.</span></span>
<span id="cb54-4"><a href="statistics-in-r-part-i.html#cb54-4" tabindex="-1"></a>zebrafish_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(length_micron <span class="sc">~</span> conc_pc, <span class="at">data =</span> zebrafish_data)</span>
<span id="cb54-5"><a href="statistics-in-r-part-i.html#cb54-5" tabindex="-1"></a></span>
<span id="cb54-6"><a href="statistics-in-r-part-i.html#cb54-6" tabindex="-1"></a><span class="co"># See the key results.</span></span>
<span id="cb54-7"><a href="statistics-in-r-part-i.html#cb54-7" tabindex="-1"></a><span class="fu">summary</span>(zebrafish_aov)</span></code></pre></div>
<pre><code>##              Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
## conc_pc       3 2485048  828349   13.64 5.97e-08 ***
## Residuals   156 9470556   60709                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We use the <code>aov()</code> function in R, where <code>length_micron</code> is the dependent variable (embryo length) and <code>conc_pc</code> is the independent variable (alcohol concentration). The function generates an ANOVA table that summarises the results of the test.</p>
<p>The output from the <code>summary()</code> function shows the following key components:</p>
<p><strong>Df (Degrees of Freedom)</strong>: This indicates how many independent pieces of information are used to estimate the variance. For <code>conc_pc</code>, the degrees of freedom is 3, as there are four levels of alcohol concentration. The residual degrees of freedom (156) corresponds to the leftover variation after accounting for the groups.</p>
<p><strong>Sum Sq (Sum of Squares)</strong>: This value represents the total variability in the data. The <code>conc_p</code>c group has a sum of squares of <strong>2,485,048</strong>, indicating a considerable amount of variation between the different alcohol concentrations.</p>
<p><strong>Mean Sq (Mean Square)</strong>: The mean square is the sum of squares divided by the corresponding degrees of freedom. This gives us an estimate of the variance within each group. The mean square for <code>conc_pc</code> is <strong>828,349</strong>.</p>
<p><strong>F value</strong>: Sometimes referred to as the “F Statistic”, this is the ratio of the mean square of the group (between-group variation) to the mean square of the residuals (within-group variation). A large F value suggests that the group means are likely different. In this case, the F value is <strong>13.64</strong>, which is quite large.</p>
<p><strong>Pr(&gt;F) (p-value)</strong>: This is the probability of observing an F value as extreme as the one calculated, under the null hypothesis that all group means are equal. A small p-value indicates strong evidence against the null hypothesis. In our case, the p-value is 5.97e-08, which is very small (much smaller than 0.05), suggesting that there is a statistically significant difference between the groups.</p>
<p>The significance codes at the bottom of the output indicate the level of significance: here, *** means a highly significant result.</p>
<p><strong>Interpretation</strong>:
Since the p-value is extremely small (much less than 0.05), we reject the null hypothesis that all group means are equal. This means there is a statistically significant difference in embryo lengths across the different alcohol concentrations. This result suggests that the alcohol concentration has a notable effect on the growth of the zebrafish embryos.</p>
<p>In the next step, we will conduct post-hoc tests to further investigate which specific groups differ from each other.</p>
</div>
<div id="post-hoc-tests-1" class="section level3 hasAnchor" number="6.1.5">
<h3><span class="header-section-number">6.1.5</span> Post-Hoc Tests<a href="statistics-in-r-part-i.html#post-hoc-tests-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As discussed previously in section <a href="summarising-data-and-anova-in-excel.html#post-hoc-tests">2.2.4</a>, after running an ANOVA, a significant result tells us that there is at least one difference among the group means, but it doesn’t specify which pairs of groups differ. To identify the specific group pairs with significant differences, we use post-hoc tests. In this section, we apply <strong>Tukey’s Honest Significant Difference (HSD)</strong> test to perform pairwise comparisons and determine which group means differ significantly.</p>
<p>In R, we can do this be extending our previuos code with two simple lines:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="statistics-in-r-part-i.html#cb56-1" tabindex="-1"></a><span class="co"># This code extends the code blocks above.</span></span>
<span id="cb56-2"><a href="statistics-in-r-part-i.html#cb56-2" tabindex="-1"></a></span>
<span id="cb56-3"><a href="statistics-in-r-part-i.html#cb56-3" tabindex="-1"></a><span class="co"># Perform TukeyHSD</span></span>
<span id="cb56-4"><a href="statistics-in-r-part-i.html#cb56-4" tabindex="-1"></a>tukey_result <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(zebrafish_aov)</span>
<span id="cb56-5"><a href="statistics-in-r-part-i.html#cb56-5" tabindex="-1"></a></span>
<span id="cb56-6"><a href="statistics-in-r-part-i.html#cb56-6" tabindex="-1"></a><span class="co"># View the results</span></span>
<span id="cb56-7"><a href="statistics-in-r-part-i.html#cb56-7" tabindex="-1"></a><span class="fu">print</span>(tukey_result)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = length_micron ~ conc_pc, data = zebrafish_data)
## 
## $conc_pc
##                diff       lwr        upr     p adj
## 1.5-0     -5.555388 -148.8123  137.70156 0.9996328
## 2-0     -110.137912 -252.4274   32.15154 0.1886631
## 2.5-0   -305.334785 -445.8132 -164.85636 0.0000005
## 2-1.5   -104.582524 -250.4332   41.26814 0.2487027
## 2.5-1.5 -299.779397 -443.8638 -155.69500 0.0000014
## 2.5-2   -195.196873 -338.3194  -52.07438 0.0029202</code></pre>
<p><strong>Interpreting the Output</strong></p>
<ul>
<li><strong>Comparisons</strong>: Each row corresponds to a comparison between two groups (e.g., 2.5-0).</li>
<li><strong>Mean Difference</strong>: The <em>diff</em> column displays the difference in means between groups.
Confidence Interval: The lwr and upr columns give the 95% confidence interval for each difference.</li>
<li><strong>Adjusted p-value</strong>: The <em>p adj</em> column provides the p-values adjusted for multiple comparisons (like for our Bonferonni correction).</li>
</ul>
<p>In the output, pairs with small p-values (e.g., 2.5-0 with a p-value of 0.0000005) indicate significant differences in group means, confirming which specific pairs show statistically significant differences. In our case, there is a signficant difference between the <code>conc_pc</code> groups: <strong>2.5-0</strong>, <strong>2.5-1.5</strong> and <strong>2.5-2</strong>.</p>
<blockquote>
<p><strong>Who Was Tukey?</strong></p>
<p>The <code>TukeyHSD()</code> test is named after <a href="https://en.wikipedia.org/wiki/John_Tukey" target="_blank">John Tukey</a>, a key figure in 20th-century statistics known for his
contributions to data analysis and multiple comparison techniques. Interestingly, while collaborating with Claude Shannon on information theory, Tukey coined the term “bit” (short for binary digit), leaving a remarkable legacy that spans statistics and computer science.</p>
</blockquote>
<p>Tukey’s Honest Significant Difference (HSD) test is a post-hoc analysis specifically designed for use after an ANOVA. It helps to identify significant pairwise group differences while controlling for the family-wise error rate (the likelihood of at least one false positive across all comparisons).</p>
<p>Tukey’s HSD is widely favoured because it strikes a balance between controlling the family-wise error rate and maintaining sensitivity to detect real differences. By contrast, Bonferroni-corrected t-tests (what we used in Excel in section @ref{post-hoc-tests}) offer a more conservative approach, dividing the significance level by the number of comparisons, which can reduce the power of the test. While Bonferroni is useful in highly exploratory settings with numerous comparisons, Tukey’s HSD is particularly effective for balanced designs in ANOVA.</p>
<p>In summary, Tukey’s HSD test provides a clear, statistically sound approach to determine specific differences between groups, supporting a rigorous interpretation of ANOVA results.</p>
</div>
</div>
<div id="two-way-anova-in-r" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Two-way ANOVA in R<a href="statistics-in-r-part-i.html#two-way-anova-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<iframe width="100%" height="400" src="https://www.youtube.com/embed/YBZK0vZTzQY?si=-j6Bh2N0D9OUygdA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
</iframe>
<p>In this section, we’ll explore how to perform a two-way ANOVA in R to evaluate the combined effects of two independent variables on a single outcome variable. For this example, imagine you are overseeing a series of experiments to understand how both <strong>pH level</strong> and <strong>temperature</strong> impact the activity of an enzyme. <a href="https://raw.githubusercontent.com/rtreharne/qs/main/data/08/activity_999.csv" target="_blank">Data</a> from ten independent groups has been consolidated to enable a comprehensive analysis.</p>
<p>It’s helpful to clarify the difference between <strong>one-way</strong> and <strong>two-way ANOVA</strong>. In a <strong>one-way ANOVA</strong>, we examine the effect of a single independent variable (or factor) on the dependent variable, allowing us to determine if there is a statistically significant difference in the outcome across different levels of that factor. However, <strong>a two-way ANOVA</strong> expands on this by allowing us to investigate two independent variables simultaneously. This approach not only assesses the effect of each factor independently (the “main effects”) but also explores the <strong>interaction effect</strong> — whether the influence of one factor on the outcome variable changes depending on the level of the other factor.</p>
<p>For instance, in our scenario, a two-way ANOVA allows us to answer questions like:</p>
<ul>
<li>Does pH level alone significantly affect enzyme activity?</li>
<li>Does temperature alone have a significant impact?</li>
<li>Most importantly, <strong>does the effect of pH on enzyme activity differ depending on the temperature?</strong></li>
</ul>
<p>Understanding these interactions is critical when both factors might influence the outcome in a combined or conditional manner, making two-way ANOVA a powerful tool for more complex experimental designs.</p>
<p>With this foundation, we can proceed to import and prepare the data for analysis.</p>
<div id="importing-and-cleaning-the-data" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> Importing and Cleaning the Data<a href="statistics-in-r-part-i.html#importing-and-cleaning-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Start a new R script and copy/paste the code block below to read the example dataset to a variable called <code>activity_data</code>.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="statistics-in-r-part-i.html#cb58-1" tabindex="-1"></a>activity_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/rtreharne/qs/main/data/08/activity_999.csv&quot;</span>)</span>
<span id="cb58-2"><a href="statistics-in-r-part-i.html#cb58-2" tabindex="-1"></a></span>
<span id="cb58-3"><a href="statistics-in-r-part-i.html#cb58-3" tabindex="-1"></a><span class="fu">head</span>(activity_data)</span></code></pre></div>
<pre><code>##   group ph temperature activity
## 1    10  7          20   0.0448
## 2     5  7          20         
## 3     9  9          40   0.0558
## 4     9  7          20    ERROR
## 5     4  9          20       -1
## 6     7  5          30   0.0423</code></pre>
<p>The dataset includes some key columns:</p>
<ul>
<li><code>group</code>: Identifier for each independent experimental group.</li>
<li><code>ph</code>: pH levels at which the enzyme activity was measured.</li>
<li><code>temperature</code>: Temperature at which the enzyme activity was measured.</li>
<li><code>activity</code>: The values in this column actually refer to the measured changes in absorbance of samples (using a spectrophotometer) over a period of time (typically minutes) - units: <span class="math inline">\(\Delta A/min\)</span>.</li>
</ul>
<p>Since <code>ph</code> and <code>temperature</code> are <strong>categorical factors</strong>, we need to ensure they are correctly set as factors in R, otherwise our ANOVA won’t work. Let’s extend our code as follows:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="statistics-in-r-part-i.html#cb60-1" tabindex="-1"></a><span class="co"># This code extends the code blocks above.</span></span>
<span id="cb60-2"><a href="statistics-in-r-part-i.html#cb60-2" tabindex="-1"></a></span>
<span id="cb60-3"><a href="statistics-in-r-part-i.html#cb60-3" tabindex="-1"></a><span class="co"># Set ph and temperature as factors</span></span>
<span id="cb60-4"><a href="statistics-in-r-part-i.html#cb60-4" tabindex="-1"></a>activity_data<span class="sc">$</span>ph <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(activity_data<span class="sc">$</span>ph)</span>
<span id="cb60-5"><a href="statistics-in-r-part-i.html#cb60-5" tabindex="-1"></a>activity_data<span class="sc">$</span>temperature <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(activity_data<span class="sc">$</span>temperature)</span></code></pre></div>
<p>We also see that some rows have the value “ERROR” or -1. We need to “clean” our dataset to ensure that all rows with these values in the activity column are removed. We can do that by extending our script with the following:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="statistics-in-r-part-i.html#cb61-1" tabindex="-1"></a><span class="co"># This code extends the code blocks above.</span></span>
<span id="cb61-2"><a href="statistics-in-r-part-i.html#cb61-2" tabindex="-1"></a></span>
<span id="cb61-3"><a href="statistics-in-r-part-i.html#cb61-3" tabindex="-1"></a><span class="co"># Make activity column numeric.</span></span>
<span id="cb61-4"><a href="statistics-in-r-part-i.html#cb61-4" tabindex="-1"></a>activity_data<span class="sc">$</span>activity <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(activity_data<span class="sc">$</span>activity)</span></code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="statistics-in-r-part-i.html#cb63-1" tabindex="-1"></a><span class="co"># Remove any rows with NA values.</span></span>
<span id="cb63-2"><a href="statistics-in-r-part-i.html#cb63-2" tabindex="-1"></a>activity_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(activity_data)</span>
<span id="cb63-3"><a href="statistics-in-r-part-i.html#cb63-3" tabindex="-1"></a></span>
<span id="cb63-4"><a href="statistics-in-r-part-i.html#cb63-4" tabindex="-1"></a><span class="co"># Insist that all values in activity column are positive. An example of subsetting with a conditional statement!</span></span>
<span id="cb63-5"><a href="statistics-in-r-part-i.html#cb63-5" tabindex="-1"></a>activity_data <span class="ot">&lt;-</span> activity_data[activity_data<span class="sc">$</span>activity <span class="sc">&gt;=</span> <span class="dv">0</span>,]</span>
<span id="cb63-6"><a href="statistics-in-r-part-i.html#cb63-6" tabindex="-1"></a></span>
<span id="cb63-7"><a href="statistics-in-r-part-i.html#cb63-7" tabindex="-1"></a><span class="co"># Re-inspect the data</span></span>
<span id="cb63-8"><a href="statistics-in-r-part-i.html#cb63-8" tabindex="-1"></a><span class="fu">head</span>(activity_data)</span></code></pre></div>
<pre><code>##    group ph temperature activity
## 1     10  7          20   0.0448
## 3      9  9          40   0.0558
## 6      7  5          30   0.0423
## 9      3  7          40   0.0418
## 11     8  5          20   0.0441
## 12     7  9          20   0.0256</code></pre>
<p>Great! Now we should only have numerical data in our activity column. Before we learn how to perform a <strong>two-way</strong> ANOVA let’s try and visualise our data.</p>
</div>
<div id="visualising-the-data" class="section level3 hasAnchor" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Visualising the data<a href="statistics-in-r-part-i.html#visualising-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Visualising data, before performing statistical tests, offers immediate insights into patterns, trends, and any anomalies that could impact analysis. It helps assess assumptions, identify outliers, and reveal interactions between variables, providing a foundation for selecting the right tests and ensuring accurate results. Although we know we’ll be performing a two-way ANOVA in this case, it’s often not always clear which test is best suited, or if assumptions have been met, until some preliminary visualisation has been carried out.</p>
<p>In this case, our good old friend the grouped boxplot might not be very helful. Boxplots are great at comparing distributions across levels of a single variable, but they’re limited when trying to visualise interactions between two factors. Instead, we can turn to a couple of alternatives that let us display the combined effect of tow factors on a dependent variable.</p>
<p><strong>1. Interaction Plot</strong></p>
<p>In an interaction plot, the levels of one variable are typically plotted on the x-axis, and the response variable is plotted on the y-axis. Different lines are drawn for each level of the second variable, and the lines’ slopes or patterns reveal if and how the variables interact.</p>
<p>Parallel lines suggest no interaction between the variables. Non-parallel lines indicate that the effect of one variable depends on the level of the other, showing an interaction.</p>
<p>Extend your script with the lines of code and run them to generate the plot shown in figure <a href="statistics-in-r-part-i.html#fig:interactionplot">6.2</a></p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="statistics-in-r-part-i.html#cb65-1" tabindex="-1"></a><span class="co"># This code extends the code blocks above.</span></span>
<span id="cb65-2"><a href="statistics-in-r-part-i.html#cb65-2" tabindex="-1"></a></span>
<span id="cb65-3"><a href="statistics-in-r-part-i.html#cb65-3" tabindex="-1"></a><span class="co"># Interaction plot of pH and Temperature on enzyme activity</span></span>
<span id="cb65-4"><a href="statistics-in-r-part-i.html#cb65-4" tabindex="-1"></a><span class="fu">interaction.plot</span>(</span>
<span id="cb65-5"><a href="statistics-in-r-part-i.html#cb65-5" tabindex="-1"></a>  activity_data<span class="sc">$</span>temperature, activity_data<span class="sc">$</span>ph, activity_data<span class="sc">$</span>activity,</span>
<span id="cb65-6"><a href="statistics-in-r-part-i.html#cb65-6" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;green&quot;</span>, <span class="st">&quot;blue&quot;</span>), <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb65-7"><a href="statistics-in-r-part-i.html#cb65-7" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">&quot;Temperature (°C)&quot;</span>, <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="st">&quot;Activity (&quot;</span><span class="sc">*</span>Delta<span class="sc">*</span><span class="st">&quot;A/min)&quot;</span>),</span>
<span id="cb65-8"><a href="statistics-in-r-part-i.html#cb65-8" tabindex="-1"></a>  <span class="at">legend=</span><span class="cn">FALSE</span></span>
<span id="cb65-9"><a href="statistics-in-r-part-i.html#cb65-9" tabindex="-1"></a>)</span>
<span id="cb65-10"><a href="statistics-in-r-part-i.html#cb65-10" tabindex="-1"></a></span>
<span id="cb65-11"><a href="statistics-in-r-part-i.html#cb65-11" tabindex="-1"></a><span class="co"># Legend placement and formatting</span></span>
<span id="cb65-12"><a href="statistics-in-r-part-i.html#cb65-12" tabindex="-1"></a><span class="fu">legend</span>(</span>
<span id="cb65-13"><a href="statistics-in-r-part-i.html#cb65-13" tabindex="-1"></a>  <span class="st">&quot;top&quot;</span>, </span>
<span id="cb65-14"><a href="statistics-in-r-part-i.html#cb65-14" tabindex="-1"></a>  <span class="at">legend =</span> <span class="fu">levels</span>(activity_data<span class="sc">$</span>ph), </span>
<span id="cb65-15"><a href="statistics-in-r-part-i.html#cb65-15" tabindex="-1"></a>  <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;green&quot;</span>, <span class="st">&quot;blue&quot;</span>), </span>
<span id="cb65-16"><a href="statistics-in-r-part-i.html#cb65-16" tabindex="-1"></a>  <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>),</span>
<span id="cb65-17"><a href="statistics-in-r-part-i.html#cb65-17" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>, </span>
<span id="cb65-18"><a href="statistics-in-r-part-i.html#cb65-18" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">&quot;pH Levels&quot;</span>,</span>
<span id="cb65-19"><a href="statistics-in-r-part-i.html#cb65-19" tabindex="-1"></a>  <span class="at">bty=</span> <span class="st">&quot;n&quot;</span></span>
<span id="cb65-20"><a href="statistics-in-r-part-i.html#cb65-20" tabindex="-1"></a>)</span></code></pre></div>
<p>Let’s break this code down so that we understand it comment by comment:</p>
<ul>
<li><code>interaction.plot()</code>:
<ul>
<li>This function creates the main plot showing how enzyme activity changes with temperature and pH.</li>
<li>Colours (<code>col = c("red", "green", "blue")</code>) are used to distinguish between the different pH levels.</li>
<li>I’ve turned the default legend off using <code>legend = False</code>, because it’s not as beautiful as I want it to be.</li>
</ul></li>
<li><code>legend()</code>:
<ul>
<li>This function adds a custom legend at the top of the plot (<code>"top"</code>) where I think it looks best and doesn’t interfere with any of the plotted lines.</li>
<li>The legend items are based on the levels of the <code>ph</code> factor.</li>
<li>The line types (<code>lty = c(3, 2, 1)</code>) specify different styles (dotted, dashed and solid) to correspond tho the lines styles generated automatically by <code>interaction.plot()</code>.</li>
<li>The <code>lwd = 2</code> argument ensures the width of the lines in the legend match the line width used in the plot.</li>
<li>The <code>bty = "n"</code> argument removes the box around the legend (this is optional, but I don’t like boxes around my legends because I’m fussy).</li>
</ul></li>
</ul>
<div class="figure"><span style="display:block;" id="fig:interactionplot"></span>
<img src="img/08/interaction_plot.png" alt="Interaction plot showing the effect of temperature and pH on enzyme activity." width="100%" />
<p class="caption">
Figure 6.2: Interaction plot showing the effect of temperature and pH on enzyme activity.
</p>
</div>
<p>How should we iterpret what is going on in figure <a href="statistics-in-r-part-i.html#fig:interactionplot">6.2</a>?</p>
<ul>
<li><strong>pH = 5</strong>: The trend shows that the enzyme activity decreases as temperature increases and that activity is higher at 20 °C than for a pH of 7 and 9.</li>
<li><strong>pH = 9</strong>: The trend shows that the enzyme activity increases as temperature increases and that activity is higher at 40 °C than for a pH of 7 and 5.</li>
<li>The lines for pH levels 5 and 9 cross each other, indicating an interaction between temperature and pH. I.e. <strong>the effect of temperature on enzyme activity changes depending on the pH level</strong>.</li>
<li><strong>pH = 7</strong>: there is little to no observable dependence of enzyme activity on temperature.</li>
</ul>
<p><strong>2. Heatmap</strong></p>
<p>Another way of visualising the above is with a <strong>heat map</strong>. Try appending the following code to your script and running the lines to get the output shown in figure <a href="statistics-in-r-part-i.html#fig:heatmap">6.3</a>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="statistics-in-r-part-i.html#cb66-1" tabindex="-1"></a><span class="co"># This code extends the code blocks above.</span></span>
<span id="cb66-2"><a href="statistics-in-r-part-i.html#cb66-2" tabindex="-1"></a></span>
<span id="cb66-3"><a href="statistics-in-r-part-i.html#cb66-3" tabindex="-1"></a><span class="co"># You&#39;ll need the reshape2 library for this one. You might need to install if first.</span></span>
<span id="cb66-4"><a href="statistics-in-r-part-i.html#cb66-4" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb66-5"><a href="statistics-in-r-part-i.html#cb66-5" tabindex="-1"></a></span>
<span id="cb66-6"><a href="statistics-in-r-part-i.html#cb66-6" tabindex="-1"></a><span class="co"># Reshape the data for heatmap visualization</span></span>
<span id="cb66-7"><a href="statistics-in-r-part-i.html#cb66-7" tabindex="-1"></a>matrix <span class="ot">&lt;-</span> <span class="fu">acast</span>(activity_data, ph <span class="sc">~</span> temperature, <span class="at">value.var =</span> <span class="st">&quot;activity&quot;</span>, mean)</span>
<span id="cb66-8"><a href="statistics-in-r-part-i.html#cb66-8" tabindex="-1"></a></span>
<span id="cb66-9"><a href="statistics-in-r-part-i.html#cb66-9" tabindex="-1"></a><span class="co"># Create a white-red color palette</span></span>
<span id="cb66-10"><a href="statistics-in-r-part-i.html#cb66-10" tabindex="-1"></a>color_palette <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">&quot;white&quot;</span>, <span class="st">&quot;red&quot;</span>))(<span class="dv">256</span>)</span>
<span id="cb66-11"><a href="statistics-in-r-part-i.html#cb66-11" tabindex="-1"></a></span>
<span id="cb66-12"><a href="statistics-in-r-part-i.html#cb66-12" tabindex="-1"></a><span class="co"># Create heatmap with blue-red colors and color key</span></span>
<span id="cb66-13"><a href="statistics-in-r-part-i.html#cb66-13" tabindex="-1"></a><span class="fu">heatmap</span>(matrix, <span class="at">Rowv =</span> <span class="cn">NA</span>, <span class="at">Colv =</span> <span class="cn">NA</span>, <span class="at">scale =</span> <span class="st">&quot;none&quot;</span>, </span>
<span id="cb66-14"><a href="statistics-in-r-part-i.html#cb66-14" tabindex="-1"></a>        <span class="at">col =</span> color_palette,  <span class="co"># Use the blue-red color palette</span></span>
<span id="cb66-15"><a href="statistics-in-r-part-i.html#cb66-15" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Temperature (°C)&quot;</span>, </span>
<span id="cb66-16"><a href="statistics-in-r-part-i.html#cb66-16" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;pH&quot;</span>, </span>
<span id="cb66-17"><a href="statistics-in-r-part-i.html#cb66-17" tabindex="-1"></a></span>
<span id="cb66-18"><a href="statistics-in-r-part-i.html#cb66-18" tabindex="-1"></a>        <span class="at">margins =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>), <span class="co"># Adjust margins if needed</span></span>
<span id="cb66-19"><a href="statistics-in-r-part-i.html#cb66-19" tabindex="-1"></a>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:heatmap"></span>
<img src="img/08/heatmap.png" alt="Heat map showing the interaction between temperature and pH on enzyme activity. Low activity is indicated by white and high activity by red." width="100%" />
<p class="caption">
Figure 6.3: Heat map showing the interaction between temperature and pH on enzyme activity. Low activity is indicated by white and high activity by red.
</p>
</div>
<p>If you can’t get this code to run then don’t worry, it’s not critically important (it won’t affect your ability to complete this week’s summative task). I just wanted to highlight that when it comes to visualisation in R, you’ve got lots of options. If you really want to understand what the code is doing then you can see what my good friend <a href="https://chatgpt.com/share/67325af3-993c-800a-9341-ade3d7194efb" target="_blank">ChatGPT</a> has to say about it.</p>
<p>I’d interpret the heatmap in figure <a href="statistics-in-r-part-i.html#fig:heatmap">6.3</a> in exactly the same way as the interaction plot. One big disadvantage however, is that it only shows the relative changes in activity - I’d need to spend a bit of time figuring out how to put a colorbar key at the side of the plot to indicate activity values with respect to colour.</p>
<p>Right now though, I think we’d really better getting to the important bit though: Finally! A Two-way ANOVA.</p>
<iframe src="https://canvaswizards.org.uk/likertysplit/qs/" width="400" style="max-width: 100%" height="600">
</iframe>
</div>
<div id="conducting-a-two-way-anova" class="section level3 hasAnchor" number="6.2.3">
<h3><span class="header-section-number">6.2.3</span> Conducting a Two-Way ANOVA<a href="statistics-in-r-part-i.html#conducting-a-two-way-anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Extend your existing script with the code below.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="statistics-in-r-part-i.html#cb67-1" tabindex="-1"></a><span class="co"># This code extends the code block above.</span></span>
<span id="cb67-2"><a href="statistics-in-r-part-i.html#cb67-2" tabindex="-1"></a></span>
<span id="cb67-3"><a href="statistics-in-r-part-i.html#cb67-3" tabindex="-1"></a><span class="co"># Perform a two-way ANOVA and save to a variable called &quot;anova_result&quot;</span></span>
<span id="cb67-4"><a href="statistics-in-r-part-i.html#cb67-4" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(activity <span class="sc">~</span> ph <span class="sc">*</span> temperature, <span class="at">data =</span> activity_data)</span>
<span id="cb67-5"><a href="statistics-in-r-part-i.html#cb67-5" tabindex="-1"></a></span>
<span id="cb67-6"><a href="statistics-in-r-part-i.html#cb67-6" tabindex="-1"></a><span class="co"># View a summary of the ANOVA</span></span>
<span id="cb67-7"><a href="statistics-in-r-part-i.html#cb67-7" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div>
<pre><code>##                 Df   Sum Sq  Mean Sq F value   Pr(&gt;F)    
## ph               2 0.000957 0.000479   25.05 1.21e-10 ***
## temperature      2 0.000490 0.000245   12.82 5.00e-06 ***
## ph:temperature   4 0.016283 0.004071  213.10  &lt; 2e-16 ***
## Residuals      250 0.004776 0.000019                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And that’s it! You’ll notice that performing a two-way ANOVA in R is almost exactly the same as performing a one-way ANOVA. The critical difference is formula we use in the <code>aov()</code>: <code>activity ~ ph * temperature</code>. We’ve included both the factors (<code>ph</code> and <code>temperatures</code>) we’re interested in within the formula separated (confusingly perhaps!) with a <code>*</code> symbol.</p>
<p>The summary table is similar to what we would expect to see for a one-way ANOVA, but it’s got a few extra rows which we should discuss:</p>
<p><strong>Main Effects (pH and Temperature)</strong>:
- Each factor - <strong>pH</strong> and <strong>Temperature</strong> - has its own row in the table. the F values and p-values for each main effect tell us if that factor alone has a statistically significant impact on enzyme activity.
- In our case, both pH and Temperature have p-values well below the 0.05 threshold. This indicates that both pH and Temperature have a strong effect on enzyme activity.
<strong>Interaction effects (pH:Temperature)</strong>:
- The interaction term, shown as <code>ph:temperature</code>, tells us if the effect of one factor depends on the level of the other factor.
- In our case, the interaction effect is highly significant (p &lt; 0.001). this suggests that <strong>the impact of pH on enzyme activity changes depending on the temperature level</strong>, and vice versa.</p>
</div>
<div id="post-hoc-tests-2" class="section level3 hasAnchor" number="6.2.4">
<h3><span class="header-section-number">6.2.4</span> Post-Hoc tests<a href="statistics-in-r-part-i.html#post-hoc-tests-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’re on the home stretch now. Now we’ve firmly established that there is some significant differences between the means of the groups we can proceed to perform our <code>TukeyHSD()</code>:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="statistics-in-r-part-i.html#cb69-1" tabindex="-1"></a><span class="co"># Perform Tukey&#39;s HSD test</span></span>
<span id="cb69-2"><a href="statistics-in-r-part-i.html#cb69-2" tabindex="-1"></a>tukey_result <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(anova_result)</span>
<span id="cb69-3"><a href="statistics-in-r-part-i.html#cb69-3" tabindex="-1"></a></span>
<span id="cb69-4"><a href="statistics-in-r-part-i.html#cb69-4" tabindex="-1"></a><span class="fu">print</span>(tukey_result)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = activity ~ ph * temperature, data = activity_data)
## 
## $ph
##              diff          lwr          upr     p adj
## 7-5  0.0044183644  0.002823274 0.0060134552 0.0000000
## 9-5  0.0037190537  0.002168714 0.0052693932 0.0000001
## 9-7 -0.0006993107 -0.002264321 0.0008657001 0.5438710
## 
## $temperature
##                diff          lwr         upr     p adj
## 30-20 -0.0002284719 -0.001817209 0.001360265 0.9386138
## 40-20  0.0027577790  0.001169042 0.004346516 0.0001698
## 40-30  0.0029862509  0.001450088 0.004522414 0.0000215
## 
## $`ph:temperature`
##                    diff           lwr          upr     p adj
## 7:20-5:20 -0.0104350631 -0.0141988811 -0.006671245 0.0000000
## 9:20-5:20 -0.0252768696 -0.0292283805 -0.021325359 0.0000000
## 5:30-5:20 -0.0169983696 -0.0207370550 -0.013259684 0.0000000
## 7:30-5:20 -0.0091688696 -0.0131203805 -0.005217359 0.0000000
## 9:30-5:20 -0.0110487484 -0.0147636697 -0.007333827 0.0000000
## 5:40-5:20 -0.0218908696 -0.0256813118 -0.018100427 0.0000000
## 7:40-5:20 -0.0093570234 -0.0132719529 -0.005442094 0.0000000
## 9:40-5:20  0.0011508951 -0.0025415202  0.004843310 0.9877802
## 9:20-7:20 -0.0148418065 -0.0185181802 -0.011165433 0.0000000
## 5:30-7:20 -0.0065633065 -0.0100099068 -0.003116706 0.0000003
## 7:30-7:20  0.0012661935 -0.0024101802  0.004942567 0.9769340
## 9:30-7:20 -0.0006136852 -0.0040344930  0.002807122 0.9997549
## 5:40-7:20 -0.0114558065 -0.0149584822 -0.007953131 0.0000000
## 7:40-7:20  0.0010780397 -0.0025589863  0.004715066 0.9912213
## 9:40-7:20  0.0115859583  0.0081896049  0.014982312 0.0000000
## 5:30-9:20  0.0082785000  0.0046278607  0.011929139 0.0000000
## 7:30-9:20  0.0161080000  0.0122396881  0.019976312 0.0000000
## 9:30-9:20  0.0142281212  0.0106018230  0.017854419 0.0000000
## 5:40-9:20  0.0033860000 -0.0003176267  0.007089627 0.1035482
## 7:40-9:20  0.0159198462  0.0120889101  0.019750782 0.0000000
## 9:40-9:20  0.0264277647  0.0228245260  0.030031003 0.0000000
## 7:30-5:30  0.0078295000  0.0041788607  0.011480139 0.0000000
## 9:30-5:30  0.0059496212  0.0025564856  0.009342757 0.0000036
## 5:40-5:30 -0.0048925000 -0.0083681555 -0.001416845 0.0005270
## 7:40-5:30  0.0076413462  0.0040303350  0.011252357 0.0000000
## 9:40-5:30  0.0181492647  0.0147807844  0.021517745 0.0000000
## 9:30-7:30 -0.0018798788 -0.0055061770  0.001746419 0.7918724
## 5:40-7:30 -0.0127220000 -0.0164256267 -0.009018373 0.0000000
## 7:40-7:30 -0.0001881538 -0.0040190899  0.003642782 1.0000000
## 9:40-7:30  0.0103197647  0.0067165260  0.013923003 0.0000000
## 5:40-9:30 -0.0108421212 -0.0142922013 -0.007392041 0.0000000
## 7:40-9:30  0.0016917249 -0.0018946761  0.005278126 0.8656961
## 9:40-9:30  0.0121996435  0.0088575587  0.015541728 0.0000000
## 7:40-5:40  0.0125338462  0.0088692746  0.016198418 0.0000000
## 9:40-5:40  0.0230417647  0.0196159301  0.026467599 0.0000000
## 9:40-7:40  0.0105079186  0.0069448352  0.014071002 0.0000000</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="statistics-in-r-part-i.html#cb71-1" tabindex="-1"></a><span class="co"># You&#39;ll need these last two lines to complete your summative test this week</span></span>
<span id="cb71-2"><a href="statistics-in-r-part-i.html#cb71-2" tabindex="-1"></a></span>
<span id="cb71-3"><a href="statistics-in-r-part-i.html#cb71-3" tabindex="-1"></a><span class="co"># Get the interaction effects table and conver to a dataframe</span></span>
<span id="cb71-4"><a href="statistics-in-r-part-i.html#cb71-4" tabindex="-1"></a><span class="co">#tukey_df &lt;- as.data.frame(tukey_result[[&quot;ph:temperature&quot;]])</span></span>
<span id="cb71-5"><a href="statistics-in-r-part-i.html#cb71-5" tabindex="-1"></a></span>
<span id="cb71-6"><a href="statistics-in-r-part-i.html#cb71-6" tabindex="-1"></a><span class="co"># Find the maximum absolute difference between the means of the ph:Temperature group-wise comparisons.</span></span>
<span id="cb71-7"><a href="statistics-in-r-part-i.html#cb71-7" tabindex="-1"></a><span class="co">#max(abs(tukey_df$diff))</span></span></code></pre></div>
<p>Woah! That’s a lot of information. Let me try to summarise what’s going on here:</p>
<p><strong>1. Main Effects</strong>:
- <strong>pH</strong>: This part shows pairwise comparisons between pH levels:
- <strong>7-5</strong>: The difference in activity between pH 7 and 5 is significant (p adj &lt; 0.05), with a positive difference of 0.0044.
- <strong>9-5</strong>: Significant difference, indicating pH 9 activity is lower than pH 5.
- <strong>9-7</strong>: Not significant (p adj = 0.484), indicating similar activity between pH 9 and 7.
- <strong>Temperature</strong>: This section compares activity across temperature levels:</p>
<ul>
<li><strong>40-20</strong> and <strong>40-30</strong> both show significant differences, suggesting that activity at 40°C is notably different from 20°C and 30°C.</li>
<li><strong>30-20</strong> is not significant, indicating similar activity between 20°C and 30°C.</li>
</ul>
<p><strong>2. Interaction Effects (pH:Temperature)</strong>:</p>
<ul>
<li>Each combination of pH and temperature levels is compared. For instance:</li>
<li><strong>7:20-5:20</strong>: Activity at pH 7 and 20°C differs significantly from pH 5 and 20°C.</li>
<li><strong>9:40-7:40</strong>: A significant difference indicates pH 9 at 40°C differs from pH 7 at 40°C.</li>
<li>Many combinations show significant differences (p adj &lt; 0.05), especially involving pH 5 at 20°C. This likely reflects the complex interaction effects found in the ANOVA, showing how specific pH and temperature combinations impact activity differently.</li>
</ul>
<p><strong>General Tips for Interpretation</strong>:</p>
<ul>
<li><strong>Significance</strong>: Look for adjusted p-values (p adj &lt; 0.05) to identify significant differences.</li>
<li><strong>Positive or Negative Differences</strong>: The diff column tells you if one level has higher or lower activity relative to another.</li>
<li><strong>Interactions</strong>: Significant differences in the <code>interaction effects</code>pH:Temperature` table suggest that the combined effect of pH and temperature is crucial for understanding enzyme activity.</li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-r-part-ii-visualisation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="statistics-in-r-part-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
