<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Statistics in R: Part II | Quantiative Skills in Biosciences I</title>
  <meta name="description" content="7 Statistics in R: Part II | Quantiative Skills in Biosciences I" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Statistics in R: Part II | Quantiative Skills in Biosciences I" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Statistics in R: Part II | Quantiative Skills in Biosciences I" />
  
  
  

<meta name="author" content="R. E. Treharne" />


<meta name="date" content="2024-10-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statistics-in-r-part-i.html"/>
<link rel="next" href="appendix.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to Excel and R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#estimating-the-volume-of-a-snail"><i class="fa fa-check"></i><b>1.1</b> Estimating the Volume of a Snail</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#download-and-import-the-csv-file"><i class="fa fa-check"></i><b>1.1.1</b> Download and Import the CSV File</a></li>
<li class="chapter" data-level="1.1.2" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#calculate-volume-v-in-excel"><i class="fa fa-check"></i><b>1.1.2</b> Calculate Volume <span class="math inline">\(V\)</span> in Excel</a></li>
<li class="chapter" data-level="1.1.3" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#add-a-linear-trendline-and-equation"><i class="fa fa-check"></i><b>1.1.3</b> Add a Linear Trendline and Equation</a></li>
<li class="chapter" data-level="1.1.4" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#estimation-of-volume-for-a-snail-with-mass-10g"><i class="fa fa-check"></i><b>1.1.4</b> Estimation of Volume for a Snail with Mass 10g</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#getting-ready-for-R"><i class="fa fa-check"></i><b>1.2</b> Getting Ready for R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#download-and-install-windows-and-mac-only"><i class="fa fa-check"></i><b>1.2.1</b> Download and Install (Windows and Mac only)</a></li>
<li class="chapter" data-level="1.2.2" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#creating-your-first-r-project-in-rstudio"><i class="fa fa-check"></i><b>1.2.2</b> Creating Your First R Project in RStudio</a></li>
<li class="chapter" data-level="1.2.3" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#something-more-complicated"><i class="fa fa-check"></i><b>1.2.3</b> Something More Complicated</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-excel-and-r.html"><a href="introduction-to-excel-and-r.html#complete-your-weekly-assignments"><i class="fa fa-check"></i><b>1.3</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html"><i class="fa fa-check"></i><b>2</b> Summarising Data and ANOVA in Excel</a>
<ul>
<li class="chapter" data-level="2.1" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#summarising-data"><i class="fa fa-check"></i><b>2.1</b> Summarising Data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#download-and-import-the-csv-file-1"><i class="fa fa-check"></i><b>2.1.1</b> Download and Import the CSV File</a></li>
<li class="chapter" data-level="2.1.2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#generating-a-summary-table"><i class="fa fa-check"></i><b>2.1.2</b> Generating a Summary Table</a></li>
<li class="chapter" data-level="2.1.3" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#presenting-your-summary-table"><i class="fa fa-check"></i><b>2.1.3</b> Presenting Your Summary Table</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#anova"><i class="fa fa-check"></i><b>2.2</b> Analysis of Variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#grouped-boxplots-in-excel"><i class="fa fa-check"></i><b>2.2.1</b> Grouped Boxplots in Excel</a></li>
<li class="chapter" data-level="2.2.2" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#constructing-testable-hypotheses"><i class="fa fa-check"></i><b>2.2.2</b> Constructing Testable Hypotheses</a></li>
<li class="chapter" data-level="2.2.3" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#performing-a-one-way-anova-in-excel"><i class="fa fa-check"></i><b>2.2.3</b> Performing a One-Way Anova in Excel</a></li>
<li class="chapter" data-level="2.2.4" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#post-hoc-tests"><i class="fa fa-check"></i><b>2.2.4</b> Performing Post-hoc Tests in Excel</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="summarising-data-and-anova-in-excel.html"><a href="summarising-data-and-anova-in-excel.html#complete-your-weekly-assignments-1"><i class="fa fa-check"></i><b>2.3</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html"><i class="fa fa-check"></i><b>3</b> Calibration Curves and Linear Regression in Excel</a>
<ul>
<li class="chapter" data-level="3.1" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#calibration-curves"><i class="fa fa-check"></i><b>3.1</b> Calibration Curves</a></li>
<li class="chapter" data-level="3.2" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#linear-regression"><i class="fa fa-check"></i><b>3.2</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#the-linear-regression-equation"><i class="fa fa-check"></i><b>3.2.1</b> The Linear Regression Equation</a></li>
<li class="chapter" data-level="3.2.2" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#performing-a-linear-regression-in-excel"><i class="fa fa-check"></i><b>3.2.2</b> Performing a Linear Regression in Excel</a></li>
<li class="chapter" data-level="3.2.3" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#interpreting-your-linear-regression"><i class="fa fa-check"></i><b>3.2.3</b> Interpreting Your Linear Regression</a></li>
<li class="chapter" data-level="3.2.4" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#making-predictions-with-our-model"><i class="fa fa-check"></i><b>3.2.4</b> Making Predictions with Our Model</a></li>
<li class="chapter" data-level="3.2.5" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#extending-to-multiple-variables"><i class="fa fa-check"></i><b>3.2.5</b> Extending to Multiple Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="calibration-curves-and-linear-regression-in-excel.html"><a href="calibration-curves-and-linear-regression-in-excel.html#complete-your-weekly-assignments-2"><i class="fa fa-check"></i><b>3.3</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html"><i class="fa fa-check"></i><b>4</b> Introduction to R: Part I</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#reading-and-inspecting-data"><i class="fa fa-check"></i><b>4.1</b> Reading and Inspecting Data</a></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#subsetting"><i class="fa fa-check"></i><b>4.2</b> Subsetting</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#slicing"><i class="fa fa-check"></i><b>4.2.1</b> Slicing</a></li>
<li class="chapter" data-level="4.2.2" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#filtering"><i class="fa fa-check"></i><b>4.2.2</b> Filtering</a></li>
<li class="chapter" data-level="4.2.3" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#so-what"><i class="fa fa-check"></i><b>4.2.3</b> So what?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#summarising-data-in-r"><i class="fa fa-check"></i><b>4.3</b> Summarising Data in R</a></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-r-part-i.html"><a href="introduction-to-r-part-i.html#complete-your-weekly-assignments-3"><i class="fa fa-check"></i><b>4.4</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html"><i class="fa fa-check"></i><b>5</b> Introduction to R part II: Visualisation</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#mushroom-compost-scenario"><i class="fa fa-check"></i><b>5.1</b> Mushroom Compost Scenario</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#the-dataset"><i class="fa fa-check"></i><b>5.1.1</b> The dataset</a></li>
<li class="chapter" data-level="5.1.2" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#further-information"><i class="fa fa-check"></i><b>5.1.2</b> Further information</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#inspecting-and-summarising"><i class="fa fa-check"></i><b>5.2</b> Inspecting and Summarising</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#summary-table"><i class="fa fa-check"></i><b>5.2.1</b> Summary Table</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#histogram"><i class="fa fa-check"></i><b>5.3</b> Histogram</a></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#grouped-boxplot"><i class="fa fa-check"></i><b>5.4</b> Grouped Boxplot</a></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#scatterplot"><i class="fa fa-check"></i><b>5.5</b> Scatterplot</a></li>
<li class="chapter" data-level="5.6" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#just-for-fun"><i class="fa fa-check"></i><b>5.6</b> Just for Fun</a></li>
<li class="chapter" data-level="5.7" data-path="introduction-to-r-part-ii-visualisation.html"><a href="introduction-to-r-part-ii-visualisation.html#complete-your-weekly-assignments-4"><i class="fa fa-check"></i><b>5.7</b> Complete your Weekly Assignments</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html"><i class="fa fa-check"></i><b>6</b> Statistics in R: Part I</a>
<ul>
<li class="chapter" data-level="6.1" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#one-way-anova-in-r"><i class="fa fa-check"></i><b>6.1</b> One-Way ANOVA in R</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#importing-data-from-an-online-source"><i class="fa fa-check"></i><b>6.1.1</b> Importing Data from an Online Source</a></li>
<li class="chapter" data-level="6.1.2" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#summarising-descriptive-statistics"><i class="fa fa-check"></i><b>6.1.2</b> Summarising (Descriptive Statistics)</a></li>
<li class="chapter" data-level="6.1.3" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#grouped-boxplots-in-r"><i class="fa fa-check"></i><b>6.1.3</b> Grouped Boxplots in R</a></li>
<li class="chapter" data-level="6.1.4" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#conducting-a-one-way-anova"><i class="fa fa-check"></i><b>6.1.4</b> Conducting a One-Way ANOVA</a></li>
<li class="chapter" data-level="6.1.5" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#post-hoc-tests-1"><i class="fa fa-check"></i><b>6.1.5</b> Post-Hoc Tests</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#two-way-anova-in-r"><i class="fa fa-check"></i><b>6.2</b> Two-way ANOVA in R</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#importing-and-cleaning-the-data"><i class="fa fa-check"></i><b>6.2.1</b> Importing and Cleaning the Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#visualising-the-data"><i class="fa fa-check"></i><b>6.2.2</b> Visualising the data</a></li>
<li class="chapter" data-level="6.2.3" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#conducting-a-two-way-anova"><i class="fa fa-check"></i><b>6.2.3</b> Conducting a Two-Way ANOVA</a></li>
<li class="chapter" data-level="6.2.4" data-path="statistics-in-r-part-i.html"><a href="statistics-in-r-part-i.html#post-hoc-tests-2"><i class="fa fa-check"></i><b>6.2.4</b> Post-Hoc tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html"><i class="fa fa-check"></i><b>7</b> Statistics in R: Part II</a>
<ul>
<li class="chapter" data-level="7.1" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#linear-regression-in-r"><i class="fa fa-check"></i><b>7.1</b> Linear Regression in R</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#reading-the-data-and-calculating-a-survival-column"><i class="fa fa-check"></i><b>7.1.1</b> Reading the data and calculating a survival column</a></li>
<li class="chapter" data-level="7.1.2" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#visualising-the-data-1"><i class="fa fa-check"></i><b>7.1.2</b> Visualising the data</a></li>
<li class="chapter" data-level="7.1.3" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#linearising-the-data"><i class="fa fa-check"></i><b>7.1.3</b> Linearising the data</a></li>
<li class="chapter" data-level="7.1.4" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#performing-a-linear-regression-in-r"><i class="fa fa-check"></i><b>7.1.4</b> Performing a Linear Regression in R</a></li>
<li class="chapter" data-level="7.1.5" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#calculating-ld50"><i class="fa fa-check"></i><b>7.1.5</b> Calculating LD50</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#multiple-linear-regression-mlr-in-r."><i class="fa fa-check"></i><b>7.2</b> Multiple Linear Regression (MLR) in R.</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#performing-an-mlr-in-r"><i class="fa fa-check"></i><b>7.2.1</b> Performing an MLR in R</a></li>
<li class="chapter" data-level="7.2.2" data-path="statistics-in-r-part-ii.html"><a href="statistics-in-r-part-ii.html#predicting-values-for-viable-counts"><i class="fa fa-check"></i><b>7.2.2</b> Predicting values for Viable Counts</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix I: Teach yourself R.</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#linkedin-learning"><i class="fa fa-check"></i>LinkedIn Learning</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#youtube"><i class="fa fa-check"></i>YouTube</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#books"><i class="fa fa-check"></i>Books</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="feedback.html"><a href="feedback.html"><i class="fa fa-check"></i>Appendix II: Feedback</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantiative Skills in Biosciences I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics-in-r-part-ii" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> Statistics in R: Part II<a href="statistics-in-r-part-ii.html#statistics-in-r-part-ii" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>If you are currently participating in a timetabled BIOS103 QS workshop, please ensure that you cover <strong>all of this section’s content</strong> and complete this week’s <strong>formative and summative assessments</strong> in the BIOS103 Canvas Course.</p>
<p>We’re going to revisit linear regression in this chapter. Our aim is to do what we were able to do with Excel in section <a href="calibration-curves-and-linear-regression-in-excel.html#linear-regression">3.2</a>, but with R. We’ll also extend our knowledge by learning how to perform a multiple linear regression (MLR), i.e. regression involving more than one independent variables.</p>
<p>The <strong>key objectives</strong> for this chapter are as follows:</p>
<ul>
<li>Linearising data with logarithms.</li>
<li>Performing a linear regression in R.</li>
<li>Visualising linear relationships and adding trendlines in R.</li>
<li>Predicting values using your regression models.</li>
<li>Extending linear regression to multiple variables (MLR).</li>
</ul>
<p>You should have a quick scroll through section <a href="calibration-curves-and-linear-regression-in-excel.html#linear-regression">3.2</a> again before you continue Yes, I mean right now.</p>
<div id="linear-regression-in-r" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Linear Regression in R<a href="statistics-in-r-part-ii.html#linear-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To keep this week’s QS relevant to what you’ve been doing in the lab, I’ve contrived the following scenario:</p>
<p>Because of your <strong>impressive data science and coding skills</strong>, you’ve been invited to join a research team investigating how cells survive under stress. Your challenge is to uncover the survival secrets of two yeast strains: the wild-type (<strong>WT</strong>) and a genetically modified mutant strain (<strong>3KO</strong>).</p>
<p>In the lab, both strains were exposed to increasing doses of hydrogen peroxide (H₂O₂)—a chemical that causes oxidative stress by damaging DNA and other essential cellular components. Your task is to help the team figure out the <strong>LD50</strong> for each strain — the dose that reduces survival by 50%.</p>
<p>This isn’t just an academic exercise. Oxidative stress is a key factor in ageing and diseases like cancer, so understanding how cells respond to it could have far-reaching implications for science and medicine.</p>
<p>Here’s your <a href="https://raw.githubusercontent.com/rtreharne/qs/refs/heads/main/data/09/yeast_999.csv" target="_blank">dataset</a> containing the results of a <strong>dose-response assay</strong>. It has the following headers:</p>
<ul>
<li><code>dose</code> (mM of H₂O₂): The level of oxidative stress applied.</li>
<li><code>strain_type</code> (WT or 3KO): The two strains being tested.</li>
<li><code>counts_per_plate</code>: The number of surviving colonies at each dose.</li>
</ul>
<p>Preliminary work has already established that at a <strong>zero dose</strong> (0 mM) of hydrogen peroxide, <strong>both</strong> yeast strains (WT and 3KO) have an average colony count of <strong>300 colonies</strong>.</p>
<p>Your challenge is to use linear regression in R to model the relationship between H₂O₂ dose and survival. By calculating and comparing the LD50 values for each strain, you’ll help the team uncover how genetic differences impact a cell’s ability to withstand damage.</p>
<p>So, let’s put your QS skills to work!</p>
<div id="reading-the-data-and-calculating-a-survival-column" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Reading the data and calculating a survival column<a href="statistics-in-r-part-ii.html#reading-the-data-and-calculating-a-survival-column" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Create a new R project and start a new script file. Read your data to a new variable called <code>yeast_data</code>. Use the <code>head()</code> function on your data to have a sneak peak. This is what you should see.</p>
<pre><code>##   dose strain_type counts_per_plate
## 1  1.0          WT              270
## 2  1.9          WT              237
## 3  2.8          WT              200
## 4  3.7          WT              190
## 5  4.6          WT              168
## 6  5.5          WT              159</code></pre>
<p>I’d like to calculate another column containing the survival as a percentage for each row. Remember, the zero dose colony counts for both WT and 3KO strains was <strong>300</strong>. I’m going to let you think about how do do this, but here’s what your head values should look like:</p>
<pre><code>##   dose strain_type counts_per_plate survival
## 1  1.0          WT              270 90.00000
## 2  1.9          WT              237 79.00000
## 3  2.8          WT              200 66.66667
## 4  3.7          WT              190 63.33333
## 5  4.6          WT              168 56.00000
## 6  5.5          WT              159 53.00000</code></pre>
</div>
<div id="visualising-the-data-1" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Visualising the data<a href="statistics-in-r-part-ii.html#visualising-the-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As ever, before deciding how to proceed with any further statistical analysis, it is good practice to visualise your data. Use the code below to generate a scatterplot that shows the dose-survival response for both yeast strains. You should see something similar to what is shown in figure <a href="statistics-in-r-part-ii.html#fig:scatterplot-1">7.1</a>.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="statistics-in-r-part-ii.html#cb74-1" tabindex="-1"></a><span class="co"># Extend your existing code with the following:</span></span>
<span id="cb74-2"><a href="statistics-in-r-part-ii.html#cb74-2" tabindex="-1"></a></span>
<span id="cb74-3"><a href="statistics-in-r-part-ii.html#cb74-3" tabindex="-1"></a></span>
<span id="cb74-4"><a href="statistics-in-r-part-ii.html#cb74-4" tabindex="-1"></a><span class="co"># Plot Dose vs Survival for Wild Type First</span></span>
<span id="cb74-5"><a href="statistics-in-r-part-ii.html#cb74-5" tabindex="-1"></a><span class="fu">plot</span>(yeast_data<span class="sc">$</span>dose[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;WT&quot;</span>], </span>
<span id="cb74-6"><a href="statistics-in-r-part-ii.html#cb74-6" tabindex="-1"></a>     yeast_data<span class="sc">$</span>survival[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;WT&quot;</span>], </span>
<span id="cb74-7"><a href="statistics-in-r-part-ii.html#cb74-7" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;p&quot;</span>,  <span class="co"># &#39;p&#39; for points only</span></span>
<span id="cb74-8"><a href="statistics-in-r-part-ii.html#cb74-8" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb74-9"><a href="statistics-in-r-part-ii.html#cb74-9" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="fu">expression</span>(Dose<span class="sc">~</span>(mM<span class="sc">~</span>H[<span class="dv">2</span>]<span class="sc">*</span>O[<span class="dv">2</span>])), </span>
<span id="cb74-10"><a href="statistics-in-r-part-ii.html#cb74-10" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Survival (%)&quot;</span>,</span>
<span id="cb74-11"><a href="statistics-in-r-part-ii.html#cb74-11" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>)</span>
<span id="cb74-12"><a href="statistics-in-r-part-ii.html#cb74-12" tabindex="-1"></a>)</span>
<span id="cb74-13"><a href="statistics-in-r-part-ii.html#cb74-13" tabindex="-1"></a></span>
<span id="cb74-14"><a href="statistics-in-r-part-ii.html#cb74-14" tabindex="-1"></a><span class="co"># Add points for Mutant Strain</span></span>
<span id="cb74-15"><a href="statistics-in-r-part-ii.html#cb74-15" tabindex="-1"></a><span class="fu">points</span>(yeast_data<span class="sc">$</span>dose[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;3KO&quot;</span>], </span>
<span id="cb74-16"><a href="statistics-in-r-part-ii.html#cb74-16" tabindex="-1"></a>       yeast_data<span class="sc">$</span>survival[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;3KO&quot;</span>], </span>
<span id="cb74-17"><a href="statistics-in-r-part-ii.html#cb74-17" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>)  <span class="co"># Color for 3KO strain</span></span>
<span id="cb74-18"><a href="statistics-in-r-part-ii.html#cb74-18" tabindex="-1"></a></span>
<span id="cb74-19"><a href="statistics-in-r-part-ii.html#cb74-19" tabindex="-1"></a><span class="co"># Add the legend</span></span>
<span id="cb74-20"><a href="statistics-in-r-part-ii.html#cb74-20" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;WT&quot;</span>, <span class="st">&quot;3KO&quot;</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:scatterplot-1"></span>
<img src="img/09/scatterplot_1.png" alt="Dose response curves for wilt type (WT) and mutant (3KO) yeast strains." width="100%" />
<p class="caption">
Figure 7.1: Dose response curves for wilt type (WT) and mutant (3KO) yeast strains.
</p>
</div>
<p>What <strong>general observations</strong> can we make from <a href="statistics-in-r-part-ii.html#fig:scatterplot-1">7.1</a>?</p>
<ul>
<li><strong>1. General Trend:</strong>
<ul>
<li>As the dose of H<sub>2</sub>O<sub>2</sub>. increases, the survival percentage decreases for both strians, indicating a negative effect of increasing oxidative stress on yeast survival.</li>
</ul></li>
<li><strong>2. Comparison of Strains:</strong>
<ul>
<li>The <strong>WT</strong> strain consistently shows higher survival percentages than the <strong>3KO</strong> strain at all doses, suggesting that the WT strain is more resistant to oxidative stress caused by H<sub>2</sub>O<sub>2</sub>.</li>
</ul></li>
<li><strong>Dose-Specific Patterns</strong>:
<ul>
<li>At lower doses (e.g., 2mM), both strains have relatively high survival percentages, but the WT strain has a clear advantage.</li>
<li>At higher doses (e.g., 8-10 mM), the surviavl percentages drop significancly for both strains, with the 3KO strain showing a much steeper decline.</li>
</ul></li>
</ul>
<p>The key implication of these observations is that compared to the WT strain, the 3KO strain’s survival is less robust to oxidative stress, potentially due to a lack of key genes.</p>
</div>
<div id="linearising-the-data" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Linearising the data<a href="statistics-in-r-part-ii.html#linearising-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Look closely at figure <a href="statistics-in-r-part-ii.html#fig:scatterplot-1">7.1</a> again. Is the relationship between survival percentage and dose linear? I don’t think so. For both yeast strains (especially the 3KO strian), my brain is trying to draw a curved line through the data points. Applying a linear model (regression) to this data would likely result in misleading predictions, such as survival percentages below 0% or above 100%. It would also likely over or under-estimate my LD50 values for each strain. I’d say that the data demonstrates a <a href="statistics-in-r-part-ii.html#non-linear"><strong>non-linear decay</strong></a>.</p>
<p>To apply linear regression appropriately, the data should first be <strong>linearised</strong>. Linearisation involves transforming the non-linear relationship into a linear one that satisfies the assumptions of linear regression. This will allow us to achieve a better model fit and to make more accurate predictions.</p>
<p>In our case we’re going to apply a <strong>logarithmic transformation</strong>. Don’t worry – I’m not expecting you to develop a deep understanding of logarithms here. In short, we use logarithmic transformations to simplify data, especially when dealing with non-linear relationships. This helps make patterns more linear and easier to interpret, without the need for complex maths (and non-linear models).</p>
<p>Let’s add the following line to our script file:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="statistics-in-r-part-ii.html#cb75-1" tabindex="-1"></a><span class="co"># Extend your existing code with the following:</span></span>
<span id="cb75-2"><a href="statistics-in-r-part-ii.html#cb75-2" tabindex="-1"></a></span>
<span id="cb75-3"><a href="statistics-in-r-part-ii.html#cb75-3" tabindex="-1"></a><span class="co"># Calculate a log_survival column</span></span>
<span id="cb75-4"><a href="statistics-in-r-part-ii.html#cb75-4" tabindex="-1"></a>yeast_data<span class="sc">$</span>log_survival <span class="ot">&lt;-</span> <span class="fu">log10</span>(yeast_data<span class="sc">$</span>survival)</span></code></pre></div>
<p>This code creates a new variable called <code>log_survival</code> in the <code>yeast_data</code> dataset by applying the <code>log10()</code> function (a base-10 logarithm) to each value in the <code>survival</code> column.</p>
<p>Let’s re-visualise the data, but now for the <code>log_survival</code> column.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="statistics-in-r-part-ii.html#cb76-1" tabindex="-1"></a><span class="co"># Extend your existing code with the following:</span></span>
<span id="cb76-2"><a href="statistics-in-r-part-ii.html#cb76-2" tabindex="-1"></a></span>
<span id="cb76-3"><a href="statistics-in-r-part-ii.html#cb76-3" tabindex="-1"></a><span class="co"># Plot Dose vs Survival for Wild Type First</span></span>
<span id="cb76-4"><a href="statistics-in-r-part-ii.html#cb76-4" tabindex="-1"></a><span class="fu">plot</span>(yeast_data<span class="sc">$</span>dose[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;WT&quot;</span>], </span>
<span id="cb76-5"><a href="statistics-in-r-part-ii.html#cb76-5" tabindex="-1"></a>     yeast_data<span class="sc">$</span>log_survival[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;WT&quot;</span>], </span>
<span id="cb76-6"><a href="statistics-in-r-part-ii.html#cb76-6" tabindex="-1"></a>     <span class="at">type =</span> <span class="st">&quot;p&quot;</span>,  <span class="co"># &#39;p&#39; for points only</span></span>
<span id="cb76-7"><a href="statistics-in-r-part-ii.html#cb76-7" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb76-8"><a href="statistics-in-r-part-ii.html#cb76-8" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="fu">expression</span>(Dose<span class="sc">~</span>(mM<span class="sc">~</span>H[<span class="dv">2</span>]<span class="sc">*</span>O[<span class="dv">2</span>])), </span>
<span id="cb76-9"><a href="statistics-in-r-part-ii.html#cb76-9" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Log (Survival (%))&quot;</span>,</span>
<span id="cb76-10"><a href="statistics-in-r-part-ii.html#cb76-10" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">1.2</span>, <span class="dv">2</span>)</span>
<span id="cb76-11"><a href="statistics-in-r-part-ii.html#cb76-11" tabindex="-1"></a>)</span>
<span id="cb76-12"><a href="statistics-in-r-part-ii.html#cb76-12" tabindex="-1"></a></span>
<span id="cb76-13"><a href="statistics-in-r-part-ii.html#cb76-13" tabindex="-1"></a><span class="co"># Add points for Mutant Strain</span></span>
<span id="cb76-14"><a href="statistics-in-r-part-ii.html#cb76-14" tabindex="-1"></a><span class="fu">points</span>(yeast_data<span class="sc">$</span>dose[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;3KO&quot;</span>], </span>
<span id="cb76-15"><a href="statistics-in-r-part-ii.html#cb76-15" tabindex="-1"></a>       yeast_data<span class="sc">$</span>log_survival[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;3KO&quot;</span>], </span>
<span id="cb76-16"><a href="statistics-in-r-part-ii.html#cb76-16" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span>)  <span class="co"># Color for 3KO strain</span></span>
<span id="cb76-17"><a href="statistics-in-r-part-ii.html#cb76-17" tabindex="-1"></a></span>
<span id="cb76-18"><a href="statistics-in-r-part-ii.html#cb76-18" tabindex="-1"></a><span class="co"># Add the legend</span></span>
<span id="cb76-19"><a href="statistics-in-r-part-ii.html#cb76-19" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">&quot;WT&quot;</span>, <span class="st">&quot;3KO&quot;</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:scatterplot-2"></span>
<img src="img/09/scatterplot_2.png" alt="Log (Survival (5) vs Dose response curves for wild type (WT) and mutant (3KO) yeast strains." width="100%" />
<p class="caption">
Figure 7.2: Log (Survival (5) vs Dose response curves for wild type (WT) and mutant (3KO) yeast strains.
</p>
</div>
<p>In the code above I’ve simply replaced any instance of <code>yeast_data$survival</code> with <code>yeast_data$log_survival</code>. I’ve also re-scaled my y-axis to values between 1.2 - 2 and updated my y-axis label to “Log (Survival (%))”. You should see a result that looks like figure <a href="statistics-in-r-part-ii.html#fig:scatterplot-2">7.2</a>. Now, my brain would be quite happy to try and draw straight lines through both the WT and 3KO series - and you know what that means, right? You got it, it’s <strong>linear regression</strong> time!</p>
<blockquote>
<h3 id="non-linear">
Non-linear Decay in Nature
</h3>
<p>Non-linear decay is a common phenomenon in nature, where processes don’t follow a straight-line pattern but instead curve as they progress. Two notable types of non-linear decay are <strong>exponential decay</strong> and <strong>sigmoidal decay</strong>.</p>
<ol style="list-style-type: decimal">
<li><strong>Exponential Decay</strong>
This occurs when a quantity decreases at a constant rate. A biological example is the decline of a population in a resource-limited environment, where individuals die off at a rate proportional to the current population size, like in certain bacteria or viruses under unfavourable conditions.</li>
<li><strong>Sigmoidal Decay</strong>
This “S” shaped curve starts slowly, then declines rapidly, and levels off at a minimum. It’s seen in biological processes like drug responses, where cells show little change at first, then quickly drop in survival, before stabilizing at low levels.</li>
</ol>
</blockquote>
</div>
<div id="performing-a-linear-regression-in-r" class="section level3 hasAnchor" number="7.1.4">
<h3><span class="header-section-number">7.1.4</span> Performing a Linear Regression in R<a href="statistics-in-r-part-ii.html#performing-a-linear-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<iframe width="100%" height="400" src="https://www.youtube.com/embed/3esibWcbz34?si=ScwovXn2AiKsVNdj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
</iframe>
<p><br></p>
<p>For the WT strain here’s how I’d do a linear regression in R:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="statistics-in-r-part-ii.html#cb77-1" tabindex="-1"></a><span class="co"># Extend your existing code with the following:</span></span>
<span id="cb77-2"><a href="statistics-in-r-part-ii.html#cb77-2" tabindex="-1"></a></span>
<span id="cb77-3"><a href="statistics-in-r-part-ii.html#cb77-3" tabindex="-1"></a><span class="co"># Create a linear model for the WT data</span></span>
<span id="cb77-4"><a href="statistics-in-r-part-ii.html#cb77-4" tabindex="-1"></a>lm_WT <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_survival <span class="sc">~</span> dose, <span class="at">data =</span> yeast_data[yeast_data<span class="sc">$</span>strain_type <span class="sc">==</span> <span class="st">&quot;WT&quot;</span>, ])</span>
<span id="cb77-5"><a href="statistics-in-r-part-ii.html#cb77-5" tabindex="-1"></a></span>
<span id="cb77-6"><a href="statistics-in-r-part-ii.html#cb77-6" tabindex="-1"></a><span class="co"># View summary</span></span>
<span id="cb77-7"><a href="statistics-in-r-part-ii.html#cb77-7" tabindex="-1"></a><span class="fu">summary</span>(lm_WT)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log_survival ~ dose, data = yeast_data[yeast_data$strain_type == 
##     &quot;WT&quot;, ])
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.023921 -0.003527 -0.002781  0.007677  0.020428 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.981583   0.008346  237.43  &lt; 2e-16 ***
## dose        -0.047769   0.001348  -35.44  5.6e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.01272 on 9 degrees of freedom
## Multiple R-squared:  0.9929, Adjusted R-squared:  0.9921 
## F-statistic:  1256 on 1 and 9 DF,  p-value: 5.601e-11</code></pre>
<p>Let’s unpack these two lines and the summary output:</p>
<ol style="list-style-type: decimal">
<li><strong>Create a linear model</strong>:</li>
</ol>
<ul>
<li><code>lm_WT &lt;-</code>: This assigns the output of the linear regression model to a new object lamed <code>lm_WT</code>. You can then refer to <code>lm_WT</code> to examine the results of the model, or make predictions, later.</li>
<li><code>lm(log_survival ~ dose, ...)</code>: The <code>lm()</code> function fits a linear regression model. Here, the dependent variable (<code>log_survival</code>) is being predicted based on the independent variable (<code>dose</code>). This means the model will examine how changes in <code>dose</code> are associated with changes in <code>log_survival</code>.</li>
<li><code>data = yeast_data[yeast_data$strain_type == "WT", ]</code>: The <code>data</code> argument specifies the dataset to use. In this case, it’s a subset of the <code>yeast_data</code> dataset. The subset is created by selecting only the rows where <code>strain_type</code> is equal to “WT”. This means the linear model is being applied <strong>only to the data for the wilt type (WT) strain</strong>.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li><strong>View summary</strong>:</li>
</ol>
<ul>
<li><code>summary(lm_WT)</code>: This command generates a summary of the linear regression model stored in the <code>lm_WT</code> object.</li>
</ul>
<h3>
<strong>Intepreting the Linear Regression Summary</strong>
</h3>
<p>The output from the <code>summary(lm_WT)</code> line indicates a strong, significantly negative relationship between <code>dose</code> and <code>log_survival</code> for the WT strain. A low residual standard error value of 0.0127 indicates that predictions are very close to observed values. An R-squared value of 0.993 indicates that <strong>99.3%</strong> of the variation in <code>log_survival</code> is explained by the <code>dose</code>. Both the intercept and slope values from the linear fit (0.9815 and -0.0478 respectively) have associated p-values &lt; 0.001 indicating that each of these coefficients are extremely significant. Overall, the model strongly supports that increasing the dose reduces survival on a logarithmic scale. It provides an excellent fit to the data with minimal residuals.</p>
</div>
<div id="calculating-ld50" class="section level3 hasAnchor" number="7.1.5">
<h3><span class="header-section-number">7.1.5</span> Calculating LD50<a href="statistics-in-r-part-ii.html#calculating-ld50" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The last thing to do then is to use our model to calculate the <strong>LD50</strong>. Remember, this is a standard measure used to indicate the dose of a substance required to kill 50% of a test population. In the code below I extract the coefficients from my linear model and substitute a y-value of log(50) (~1.70) into my formula to predict the dose value:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="statistics-in-r-part-ii.html#cb79-1" tabindex="-1"></a><span class="co">#  Extend your existing code with the following:</span></span>
<span id="cb79-2"><a href="statistics-in-r-part-ii.html#cb79-2" tabindex="-1"></a></span>
<span id="cb79-3"><a href="statistics-in-r-part-ii.html#cb79-3" tabindex="-1"></a><span class="co"># Get your model coefficients</span></span>
<span id="cb79-4"><a href="statistics-in-r-part-ii.html#cb79-4" tabindex="-1"></a>intercept_WT <span class="ot">&lt;-</span> lm_WT<span class="sc">$</span>coeff[<span class="dv">1</span>] <span class="co"># Extract the intercept</span></span>
<span id="cb79-5"><a href="statistics-in-r-part-ii.html#cb79-5" tabindex="-1"></a>slope_WT <span class="ot">&lt;-</span> lm_WT<span class="sc">$</span>coeff[<span class="dv">2</span>] <span class="co"># Extract the slope</span></span>
<span id="cb79-6"><a href="statistics-in-r-part-ii.html#cb79-6" tabindex="-1"></a></span>
<span id="cb79-7"><a href="statistics-in-r-part-ii.html#cb79-7" tabindex="-1"></a><span class="co"># Calculate the dose predicted at a log_survival of log(50)</span></span>
<span id="cb79-8"><a href="statistics-in-r-part-ii.html#cb79-8" tabindex="-1"></a>ld50_WT <span class="ot">&lt;-</span> (<span class="fu">log10</span>(<span class="dv">50</span>) <span class="sc">-</span> intercept_WT)<span class="sc">/</span>slope_WT</span>
<span id="cb79-9"><a href="statistics-in-r-part-ii.html#cb79-9" tabindex="-1"></a></span>
<span id="cb79-10"><a href="statistics-in-r-part-ii.html#cb79-10" tabindex="-1"></a><span class="co"># print ld50_WT</span></span>
<span id="cb79-11"><a href="statistics-in-r-part-ii.html#cb79-11" tabindex="-1"></a><span class="fu">print</span>(ld50_WT)</span></code></pre></div>
<pre><code>## (Intercept) 
##    5.916249</code></pre>
<p>And there you have it! My <strong>LD50</strong> value for my <strong>wild type</strong> (WT) strain is 5.92 mM (2 d.p). I can update my figure <a href="statistics-in-r-part-ii.html#fig:scatterplot-2">7.2</a> to show my line of best fit generated by my linear model and annotate the line with my LD50 value for WT using the following code:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="statistics-in-r-part-ii.html#cb81-1" tabindex="-1"></a><span class="co">#  Extend your existing code with the following:</span></span>
<span id="cb81-2"><a href="statistics-in-r-part-ii.html#cb81-2" tabindex="-1"></a></span>
<span id="cb81-3"><a href="statistics-in-r-part-ii.html#cb81-3" tabindex="-1"></a><span class="co"># Add regression line</span></span>
<span id="cb81-4"><a href="statistics-in-r-part-ii.html#cb81-4" tabindex="-1"></a><span class="fu">abline</span>(lm_WT)</span>
<span id="cb81-5"><a href="statistics-in-r-part-ii.html#cb81-5" tabindex="-1"></a></span>
<span id="cb81-6"><a href="statistics-in-r-part-ii.html#cb81-6" tabindex="-1"></a><span class="co"># Annotate the plot with the WT LD50</span></span>
<span id="cb81-7"><a href="statistics-in-r-part-ii.html#cb81-7" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ld50_WT, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)  <span class="co"># Vertical dotted line at LD50</span></span>
<span id="cb81-8"><a href="statistics-in-r-part-ii.html#cb81-8" tabindex="-1"></a><span class="fu">text</span>(ld50_WT, log50, <span class="at">labels =</span> <span class="fu">paste</span>(<span class="st">&quot;LD50 =&quot;</span>, <span class="fu">round</span>(ld50_WT, <span class="dv">2</span>)), <span class="at">pos =</span> <span class="dv">4</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:scatterplot-3"></span>
<img src="img/09/scatterplot_3.png" alt="Log (Survival (%) vs Dose response curves for wild type (WT) and mutant (3KO) yeast strains. Straight black line indicates result of linear regression model for WT. Vertical dotted red line indicates LD50 value for WT." width="100%" />
<p class="caption">
Figure 7.3: Log (Survival (%) vs Dose response curves for wild type (WT) and mutant (3KO) yeast strains. Straight black line indicates result of linear regression model for WT. Vertical dotted red line indicates LD50 value for WT.
</p>
</div>
<p>Can you do the same for the <strong>3KO</strong> mutant strain? <strong>You’ll need to if you want to complete this week’s summative test</strong>.</p>
<iframe src="https://canvaswizards.org.uk/likertysplit/qs/" width="400" style="max-width: 100%" height="600">
</iframe>
</div>
</div>
<div id="multiple-linear-regression-mlr-in-r." class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Multiple Linear Regression (MLR) in R.<a href="statistics-in-r-part-ii.html#multiple-linear-regression-mlr-in-r." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can extend our knowledge of regression by exploring <strong>Multiple Linear Regression (MLR)</strong>. Unlike simple linear regression, which focuses on a single predictor, MLR enables us to account for the effects of multiple factors <strong>simultaneously</strong>, making it ideal for more complex real-world problems.</p>
<p>As an example, let’s revisit our <strong>MegaMush</strong> scenario from Chapter 5. We explored how the dependent variable, <strong>Viable Counts</strong> (VC), is influenced by independent variables, temperature and moisture. I finished the chapter with figure <a href="introduction-to-r-part-ii-visualisation.html#fig:plotly">5.4</a>, a 3D scatterplot showing that all the data aligns with a flat plane rather than a single line of best fit between any pair of variables. We can use MLR to determine the equation of that flat plane and then predict <strong>VC</strong> for any combination of temperature and moisture within the measured range. Such an analysis would be extremely powerful for anyone wanting to fine-tune processes to finely control the resultant the <strong>VC</strong>.</p>
<div id="performing-an-mlr-in-r" class="section level3 hasAnchor" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Performing an MLR in R<a href="statistics-in-r-part-ii.html#performing-an-mlr-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<iframe width="100%" height="400" src="https://www.youtube.com/embed/KdLIXQMQZ_c?si=KRms0Xmu54eoYmAw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
</iframe>
<p><br></p>
<p>Let’s do it! Start a new script file in your project for this week and run the following code:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="statistics-in-r-part-ii.html#cb82-1" tabindex="-1"></a><span class="co"># Read the data from a URL</span></span>
<span id="cb82-2"><a href="statistics-in-r-part-ii.html#cb82-2" tabindex="-1"></a>compost_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/rtreharne/qs/refs/heads/main/data/05/compost_999.csv&quot;</span>)</span>
<span id="cb82-3"><a href="statistics-in-r-part-ii.html#cb82-3" tabindex="-1"></a></span>
<span id="cb82-4"><a href="statistics-in-r-part-ii.html#cb82-4" tabindex="-1"></a><span class="co"># Create an MLR model</span></span>
<span id="cb82-5"><a href="statistics-in-r-part-ii.html#cb82-5" tabindex="-1"></a>lm_compost <span class="ot">&lt;-</span> <span class="fu">lm</span>(Viable.counts <span class="sc">~</span> Temperature <span class="sc">*</span> Moisture, <span class="at">data =</span> compost_data)</span>
<span id="cb82-6"><a href="statistics-in-r-part-ii.html#cb82-6" tabindex="-1"></a></span>
<span id="cb82-7"><a href="statistics-in-r-part-ii.html#cb82-7" tabindex="-1"></a><span class="co"># Inspect the result of the model</span></span>
<span id="cb82-8"><a href="statistics-in-r-part-ii.html#cb82-8" tabindex="-1"></a><span class="fu">summary</span>(lm_compost)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Viable.counts ~ Temperature * Moisture, data = compost_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.6152 -0.3811 -0.0023  0.3978  1.7748 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          171.269754   6.665708  25.694   &lt;2e-16 ***
## Temperature           -1.382293   0.116104 -11.906   &lt;2e-16 ***
## Moisture               0.886532   0.089907   9.861   &lt;2e-16 ***
## Temperature:Moisture  -0.001503   0.001561  -0.963    0.336    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5806 on 496 degrees of freedom
## Multiple R-squared:  0.9942, Adjusted R-squared:  0.9941 
## F-statistic: 2.811e+04 on 3 and 496 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Wow. That was easy! You’ll notice that the only real difference was in the formula argument of the <code>lm()</code> function. You’ve incorporated both independent variables using <code>Viable.counts ~ Temperature * Moisture</code>. This is reminiscent of your two-way ANOVA from last week. Let’s interpret the interesting bits of the summary output:</p>
<ul>
<li><strong>Temperature</strong>: For every 1-unit increase in <strong>Temperature</strong>, <strong>VC</strong> decreases by 1.38 units (highly significant, p &lt; 2e-16!).</li>
<li><strong>Moisture</strong>: For every 1-unit increase in <strong>Moisture</strong>, <strong>VC</strong> increases by 0.89 units (highly significant, p &lt; 2e-16!).</li>
<li><strong>Temperature:Moisture interaction</strong>: Just like with out two-way ANOVA we get a line in our summary that tells us if there is any significant interaction between our independent variables. Interestingly, in this case the interaction effect is small and not statistically significant (p = 0.36).</li>
<li><strong>Model Fit</strong>:
<ul>
<li>Residual standard error: 0.58 (very low!)</li>
<li>Adjusted R<sup>2</sup>: 0.9941 - The model can explain 99.41% of the variance in the dataset.</li>
<li>Overall model significance: p &lt; 2.2e-16</li>
</ul></li>
</ul>
<p>In conclusion, the multi-linear regression model provides a strong fit to the data. Both <strong>Temperature</strong> and <strong>Moisture</strong> significantly impact the <strong>Viable Counts</strong>, but their interaction is not statistically significant.</p>
</div>
<div id="predicting-values-for-viable-counts" class="section level3 hasAnchor" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Predicting values for Viable Counts<a href="statistics-in-r-part-ii.html#predicting-values-for-viable-counts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You can now proceed to make a prediction for VC values by inputting any combination of Temperature and Moisture co-ordinates from the measured range of data. It would be a bad idea to try and predict VC for any temperatures/moisture from outside the range because you really don’t know if the behavior outside of this range will remain linear.</p>
<p>You can use your model object <code>lm_compost</code> to predict VC using few lines of R code. I am going to be a bit mean here and let you figure out the best way to do this yourselves (there will be more than one way to do it!). I don’t care how you go about this - Google, ChatGPT etc - do whatever it takes. Remember to make use of this week’s formative test to check your results first before attempting the summative test. <strong>If you’ve cracked it then I encourage you to share your solutions in the Workshop channel in Microsoft Teams</strong>.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="statistics-in-r-part-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
